### ISSUE TITLE
Test attribute is created 3 times when discovery is done

### ISSUE THREAD

**Issue by nohwnd** [microsoft/testfx#1056]
When discovery happens the test method attribute is created 3 times. I found this when looking into our vstest tests that are testing discovery (DiscoverTests.CancelTestDiscovery) 

The [TestMethod] attribute stalls for 10s in the constructor, but it takes 3 times that to report the test as discovered. (in TestAssets.sln, DiscoveryTestProject. LongDiscoveryTestClass) 

```cs
namespace DiscoveryTestProject3
{
    [TestClass]
    public class LongDiscoveryTestClass
    {
        [MyTestMethod]
        public void CustomTestMethod()
        {

        }
    }

    internal class MyTestMethodAttribute : TestMethodAttribute
    {
        public MyTestMethodAttribute()
        {
            System.IO.File.AppendAllText(@"C:\temp\tmp.txt", System.Environment.StackTrace.ToString() + "\n\n");
            Thread.Sleep(10000);
        }
    }
}
```

Writing callstacks from the ctor results in:

```
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at DiscoveryTestProject3.MyTestMethodAttribute..ctor() in C:\p\vstest\test\TestAssets\DiscoveryTestProject\LongDiscoveryTestClass.cs:line 24
   at System.RuntimeTypeHandle.CreateCaInstance(RuntimeType type, IRuntimeMethodInfo ctor)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ReflectionOperations.GetCustomAttributes(MemberInfo memberInfo, Boolean inherit)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Helpers.ReflectHelper.GetCustomAttributes(MemberInfo memberInfo, Boolean inherit)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Helpers.ReflectHelper.GetAttributes(MemberInfo memberInfo, Boolean inherit)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Helpers.ReflectHelper.IsAttributeDefined(MemberInfo memberInfo, Type attributeType, Boolean inherit)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Discovery.TestMethodValidator.IsValidTestMethod(MethodInfo testMethodInfo, Type type, ICollection`1 warnings)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Discovery.TypeEnumerator.GetTests(ICollection`1 warnings)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Discovery.AssemblyEnumerator.DiscoverTestsInType(String assemblyFileName, String runSettingsXml, Assembly assembly, Type type, List`1 warningMessages, Boolean discoverInternals, TestDataSourceDiscoveryOption discoveryOption)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Discovery.AssemblyEnumerator.EnumerateAssembly(String assemblyFileName, ICollection`1& warnings)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
   at System.Runtime.Remoting.Messaging.ServerObjectTerminatorSink.SyncProcessMessage(IMessage reqMsg)
   at System.Runtime.Remoting.Messaging.ServerContextTerminatorSink.SyncProcessMessage(IMessage reqMsg)
   at System.Runtime.Remoting.Channels.CrossContextChannel.SyncProcessMessageCallback(Object[] args)
   at System.Threading.Thread.InternalCrossContextCallback(Context ctx, IntPtr ctxID, Int32 appDomainID, InternalCrossContextDelegate ftnToCall, Object[] args)
   at System.Runtime.Remoting.Channels.CrossContextChannel.SyncProcessMessage(IMessage reqMsg)
   at System.Runtime.Remoting.Channels.ChannelServices.SyncDispatchMessage(IMessage msg)
   at System.Runtime.Remoting.Channels.CrossAppDomainSink.DoDispatch(Byte[] reqStmBuff, SmuggledMethodCallMessage smuggledMcm, SmuggledMethodReturnMessage& smuggledMrm)
   at System.Runtime.Remoting.Channels.CrossAppDomainSink.DoTransitionDispatchCallback(Object[] args)

   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at DiscoveryTestProject3.MyTestMethodAttribute..ctor() in C:\p\vstest\test\TestAssets\DiscoveryTestProject\LongDiscoveryTestClass.cs:line 24
   at System.RuntimeTypeHandle.CreateCaInstance(RuntimeType type, IRuntimeMethodInfo ctor)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Helpers.ReflectHelper.GetCustomAttributes(MemberInfo memberInfo, Type type, Boolean inherit)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Helpers.ReflectHelper.GetCustomAttribute(MemberInfo attributeProvider, Type type)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Discovery.TypeEnumerator.GetTestFromMethod(MethodInfo method, Boolean isDeclaredInTestTypeAssembly, ICollection`1 warnings)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Discovery.TypeEnumerator.GetTests(ICollection`1 warnings)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Discovery.AssemblyEnumerator.DiscoverTestsInType(String assemblyFileName, String runSettingsXml, Assembly assembly, Type type, List`1 warningMessages, Boolean discoverInternals, TestDataSourceDiscoveryOption discoveryOption)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Discovery.AssemblyEnumerator.EnumerateAssembly(String assemblyFileName, ICollection`1& warnings)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
   at System.Runtime.Remoting.Messaging.ServerObjectTerminatorSink.SyncProcessMessage(IMessage reqMsg)
   at System.Runtime.Remoting.Messaging.ServerContextTerminatorSink.SyncProcessMessage(IMessage reqMsg)
   at System.Runtime.Remoting.Channels.CrossContextChannel.SyncProcessMessageCallback(Object[] args)
   at System.Threading.Thread.InternalCrossContextCallback(Context ctx, IntPtr ctxID, Int32 appDomainID, InternalCrossContextDelegate ftnToCall, Object[] args)
   at System.Runtime.Remoting.Channels.CrossContextChannel.SyncProcessMessage(IMessage reqMsg)
   at System.Runtime.Remoting.Channels.ChannelServices.SyncDispatchMessage(IMessage msg)
   at System.Runtime.Remoting.Channels.CrossAppDomainSink.DoDispatch(Byte[] reqStmBuff, SmuggledMethodCallMessage smuggledMcm, SmuggledMethodReturnMessage& smuggledMrm)
   at System.Runtime.Remoting.Channels.CrossAppDomainSink.DoTransitionDispatchCallback(Object[] args)

   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at DiscoveryTestProject3.MyTestMethodAttribute..ctor() in C:\p\vstest\test\TestAssets\DiscoveryTestProject\LongDiscoveryTestClass.cs:line 24
   at System.RuntimeTypeHandle.CreateCaInstance(RuntimeType type, IRuntimeMethodInfo ctor)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Helpers.ReflectHelper.GetCustomAttributes(MemberInfo memberInfo, Type type, Boolean inherit)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Helpers.ReflectHelper.GetAttributes[T](MethodBase methodBase, Boolean inherit)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Discovery.AssemblyEnumerator.TryProcessTestDataSourceTests(UnitTestElement test, TestMethodInfo testMethodInfo, List`1 tests)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Discovery.AssemblyEnumerator.DynamicDataAttached(IDictionary`2 sourceLevelParameters, Assembly assembly, UnitTestElement test, List`1 tests)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Discovery.AssemblyEnumerator.DiscoverTestsInType(String assemblyFileName, String runSettingsXml, Assembly assembly, Type type, List`1 warningMessages, Boolean discoverInternals, TestDataSourceDiscoveryOption discoveryOption)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Discovery.AssemblyEnumerator.EnumerateAssembly(String assemblyFileName, ICollection`1& warnings)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
   at System.Runtime.Remoting.Messaging.ServerObjectTerminatorSink.SyncProcessMessage(IMessage reqMsg)
   at System.Runtime.Remoting.Messaging.ServerContextTerminatorSink.SyncProcessMessage(IMessage reqMsg)
   at System.Runtime.Remoting.Channels.CrossContextChannel.SyncProcessMessageCallback(Object[] args)
   at System.Threading.Thread.InternalCrossContextCallback(Context ctx, IntPtr ctxID, Int32 appDomainID, InternalCrossContextDelegate ftnToCall, Object[] args)
   at System.Runtime.Remoting.Channels.CrossContextChannel.SyncProcessMessage(IMessage reqMsg)
   at System.Runtime.Remoting.Channels.ChannelServices.SyncDispatchMessage(IMessage msg)
   at System.Runtime.Remoting.Channels.CrossAppDomainSink.DoDispatch(Byte[] reqStmBuff, SmuggledMethodCallMessage smuggledMcm, SmuggledMethodReturnMessage& smuggledMrm)
   at System.Runtime.Remoting.Channels.CrossAppDomainSink.DoTransitionDispatchCallback(Object[] args)


```

Is there somthing we can do about this? Is this a potential perf improvement?

**Comment by Evangelink** [comment]
We could introduce some caching mechanism for the various attributes but that doesn't seem ideal. 

Attribute objects are supposed to be transient and in general a constructor should be fast and slower initializations should be moved to methods (ideally `async`).

I guess the gain would be usually neglectable except for "badly designed" attributes as the one showed above.

Based on that, I will move forward by closing this issue. If we have data that this is a common pattern, we could revisit this decision.
