### ISSUE TITLE
If using extension of TestMethodAttribute then please contact vendor. Error message: An item with the same key has already been added. Key: out

### ISSUE THREAD

**Issue by Evangelink** [microsoft/testfx#1107]
## Steps to reproduce

TP acceptance test on mac: https://dev.azure.com/dnceng/public/_build/results?buildId=1773100&view=logs&j=2728e4e0-66e6-50b3-5810-75ad575aa0cd&t=f5344cc9-2213-5f5c-7a1e-3449f7e86afd

Stack trace:
```
Failed RunningTestWithAFailingDebugAssertDoesNotCrashTheHostingProcess (Runner = netcoreapp2.1, TargetFramework = netcoreapp2.1, InProcess) [21 ms]
  Error Message:
   Exception thrown while executing test. If using extension of TestMethodAttribute then please contact vendor. Error message: An item with the same key has already been added. Key: out, Stack trace:    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadSafeStringWriter.GetOrAddStringBuilder()
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadSafeStringWriter..ctor(IFormatProvider formatProvider, String outputType)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.LogMessageListener..ctor(Boolean captureDebugTraces)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestMethodInfo.Invoke(Object[] arguments)
   at Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute.Execute(ITestMethod testMethod)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestMethodRunner.ExecuteTest(TestMethodInfo testMethodInfo)
```

**Comment by Evangelink** [comment]
@nohwnd I think you fixed this issue already, right?

**Comment by nohwnd** [comment]
Yes, introduced in mstest 2.2.9 fixed in mstest 2.2.10
