### ISSUE TITLE
getting an exception on RunSelectedOperation with  VS 2022 17.5.0

### ISSUE THREAD

**Issue by fforjan** [microsoft/testfx#1605]
## Describe the bug
The unit tests do not run any more and need to restart Visual Studio.

## Steps To Reproduce
There is not clear way to reproduce the issue.
I have the feeling it is a combination of changing branches under git AND switching between Debug, Release and other configurtion

## Expected behavior
I should be able to run unit test.

## Actual behavior
```
[2/22/2023 4:41:54.234 PM]  Hierarchy Collapsing node 178747
[2/22/2023 4:41:54.299 PM]  Hierarchy Collapsing node 178747
[2/22/2023 4:41:58.026 PM]  Interrupt: Enqueueing RunSelectedOperation
[2/22/2023 4:41:58.026 PM]  Enqueue operation 'RunSelectedOperation', hashcode:53842738 
[2/22/2023 4:41:58.026 PM]  Operation left in the the queue: 1
[2/22/2023 4:41:58.026 PM]  	'RunSelectedOperation', hashcode:53842738
[2/22/2023 4:41:58.026 PM]  

[2/22/2023 4:41:58.027 PM]  Operation Dequeue : 'RunSelectedOperation'
[2/22/2023 4:41:58.039 PM] [Error] System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.VisualStudio.TestWindow.Controller.TestContainerConfigurationQueryByTestsBase.<GetTestContainerConfigurations>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Controller.TestContainerConfigurationQueryByTestsBase.<GetContainersToUpdateInternalAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Controller.TestContainerConfigurationQuery.<GetAndCacheContainersToUpdateAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Controller.RunOperation.<FindChangedContainersAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Controller.DiscoveryOperation.<DetectChangedContainersAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Controller.RunOperation.<RunTestsAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.TestWindow.Controller.RunOperation.<RunTestsAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Controller.RunOperation.<ExecuteInternalAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Controller.Operation.<<ExecuteAsync>b__43_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.<CallWithCatchAsync>d__11`1.MoveNext()
[2/22/2023 4:41:58.099 PM]  Update Test run progress to 0/100.
```
Tests are not running 

## Additional context
Using Microsoft Visual Studio Enterprise 2022 (64-bit) - Current Version 17.5.0
nuget reference Microsoft.NET.Test.Sdk 17.4.1
nuget reference MSTest 3.0.2

Extra question, some of our build machines for some reasons have old  VS2022 versions and the dev team is still with VS 2022 17.4.5. When is it recommended to upgrade Microsoft.NET.Test.Sdk to its latest version  -17.5- following the visual studio release

[AB#1754964](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1754964)

**Comment by engyebrahim** [comment]
Hi [fforjan](https://github.com/fforjan),
I tried to reproduce the issue but I don't get it please provide us by spastic steps or sample project to reproduce.

for the update we always recommend to use the latest versions.

**Comment by fforjan** [comment]
@engyebrahim  unfortunately I do not have easy step to reproduce, it seems be random after using Visual Studio for hours/day :(

**Comment by Evangelink** [comment]
@AbhitejJohn @peterwald this is for you as it's on VS TE side.

**Comment by AbhitejJohn** [comment]
Seems like this could be related to https://developercommunity.visualstudio.com/t/Cant-run-tests:-SystemArgumentExceptio/10256516. Do the comments shared there help @fforjan?

**Comment by fforjan** [comment]
@AbhitejJohn in my case restarting visual studio works too, so not a big issue. It is just developers in my team had the issue #4208 and now potentially this one.
They are not happy about MSTest V3 disturbance and running unit tests is a activity you do every minutes so impacting them easily :/

**Comment by Evangelink** [comment]
Sorry about the different issues your team has been facing! 

MSTest v2 was in a bit of an unstable state and we had to work hard to try to stabilize it, in the process we had a couple of major updates to improve behaviour in VS but it turns out they had some unexpected side effects.

I don't see anything that can be done on MSTest (outside of downgrading the dependency to Test Platform).

@fforjan is it ok to close the issue as-is?

**Comment by fforjan** [comment]
Yes, It would be ok, it seems you are already tracking this with the community report. So closing as such
