### ISSUE TITLE
AZDO failing on executor://mstestadapter/v2': Could not load file or assembly Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions

### ISSUE THREAD

**Issue by ani-mal** [microsoft/testfx#1689]
## Describe the bug

I am running into the following error inside Azure Dev Ops using the `VSTest@2` Task:

`.yml` pipeline tasks that are throwing the error:

```.yml 
parameters:
  - name: Platform
    type: string

steps:
  - task: VisualStudioTestPlatformInstaller@1
    displayName: 'Install Latest VSTest'
    inputs:
      packageFeedSelector: 'nugetOrg'
      versionSelector: 'latestStable'

  - task: VSTest@2
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        **\bin\Release\*Tests.dll
        **\bin\${{parameters.Platform}}\Release\*Tests.dll
        !**\*TestAdapter.dll
        !**\obj\**
      searchFolder: '$(System.DefaultWorkingDirectory)'
      vsTestVersion: '16.0'
      codeCoverageEnabled: true
      platform: '${{parameters.Platform}}'
    displayName: 'Run CSharp Unit Tests'
```

```.cmd
##[error]An exception occurred while invoking executor 'executor://mstestadapter/v2': Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.TestFramework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
##[error]Stack trace:
##[error]   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.MSTestExecutor.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle)
##[error]   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.RunTestsWithSources.InvokeExecutor(LazyExtension`2 executor, Tuple`2 executorUriExtensionTuple, RunContext runContext, IFrameworkHandle frameworkHandle)
##[error]   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.<>c__DisplayClass48_0.<RunTestInternalWithExecutors>b__0()
##[error]   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformThread.<>c__DisplayClass0_0.<Run>b__0()
##[error]--- End of stack trace from previous location where exception was thrown ---
##[error]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
##[error]   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformThread.Run(Action action, PlatformApartmentState apartmentState, Boolean waitForCompletion)
##[error]   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.TryToRunInSTAThread(Action action, Boolean waitForCompletion)
##[error]   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestInternalWithExecutors(IEnumerable`1 executorUriExtensionMap, Int64 totalTests)

```

 I tried with both `MSTest.TestAdapter` and `MSTest.TestFramework` version `2.2.10` and the latest `3.0.4`. This issue does not happens when building and running the unit tests locally, but I get the same error listed above when trying to run this task on azure dev ops. 
 
 
## Steps To Reproduce

Note that we would be glad if you could enclose a repro (zip or link to some GitHub project).
-->

## Expected behavior
Able to run unit test on azure dev ops without `executor://mstestadapter/v2': Could not load file or assembly` error

## Actual behavior
Error listed above 
## Additional context
- `17.6.2` is the version of the  Microsoft.TestPlatform that gets installed on the agent through the `VisualStudioTestPlatformInstaller@1` task
- The solution I am trying to build is targeting VS2019 and using .NET 4.7.2

**Comment by Kawemi** [comment]
The same issue arose in my CI build on AZDO, but my local environment also seems to be affected. I get the same error when just running `dotnet test` on my solution.

**Comment by engyebrahim** [comment]
Hi @ani-mal !

so can I close the issue as you resolved it?

**Comment by ani-mal** [comment]
@engyebrahim I will close it! Thank you for following up!
