### ISSUE TITLE
Separate Test Results and Logs for AssemblyInitialize, AssemblyCleanup, ClassInitialize and ClassCleanup

### ISSUE THREAD

**Issue by Gracie-Work** [microsoft/testfx#1698]
## Summary

Nowadays, MSTest only returns test results and appends the logs to the first executed test case for AssemblyInitialize and ClassInitialize, and appends the logs to the last executed test case for ClassCleanup logs and AssemblyCleanup.
 
## Background and Motivation
Substrate engineers highly depend on test logs and results for debugging failures. When the logs are appended to the first executed or the last one, it makes it difficult for users to debug it or find the logs. We also have test failure analysis based on different types of failures. Especially when there are failures in Initialize, we encourage users to dig more into the failures before checking in. But since there are no AssemblyInitialize/ClassInitialize results, it's impossible for us to provide the failure type. 

## Proposed Feature
MSTest framework to return results as follows:
•    AssemblyInitialize Failed/Succeeded – Output logs
•    ClassInitialize Failed/Succeeded – Output logs
•    TestMethod1 Failed/Succeeded – Output logs
•    TestMethod2 Failed/Succeeded – Output logs
•    ClassCleanup Failed/Succeeded -Output logs
•    AssemblyCleanup Failed/Succeeded -Output logs

**Comment by Evangelink** [comment]
Hi @Gracie-Work,

When you are talking about separate logs, do you mean a separate log file? Or do you mean a separate entry in the trx (or VS) or some other tool?

**Comment by Gracie-Work** [comment]
Similar to the issue [#1497 ](https://github.com/microsoft/testfx/issues/1497), we need treat these results as "test case" but different type of test cases. Slightly different from the former issue, we'd like to get the separated result entry in below APIs first. Which I assume it leverages vstest.console.exe in backend.

• Microsoft.VisualStudio.TestPlatform.ObjectModel 
• Microsoft.TestPlatform.TranslationLayer 

In the ideal world, the experience should be unified in vstest.console.exe, TranslationLayer API, VS test explorer.

**Comment by Evangelink** [comment]
Fixed by #2904

**Comment by Vincezhaoc** [comment]
Hi @Evangelink,

I have some questions based on [change log 3.5.0](https://github.com/microsoft/testfx/blob/main/docs/Changelog.md#350---2024-07-15) and [PR2904](https://github.com/microsoft/testfx/pull/2904).

### Purpose for finding this feature.
If an `Exception` is thrown from `[AssemblyInitialize]`, `[AssemblyCleanup]`, `[ClassInitialize]` and `[ClassCleanup]`, it will be bound to the test methods' information view. I am tring to find any features support by mstest to mark the four attributes as separate entries.

### Description
I am aware of MSTest should support `[AssemblyInitialize]`, `[AssemblyCleanup]`, `[ClassInitialize]` and `[ClassCleanup]` as separate entries in Visual Studio's `Test Explorer` and in TRX log. However, after upgrading `MSTest.TestFramework`, `MSTest.TestAdapter` and `MSTest.Sdk` to version `3.5.2`, my local Visual Studio (Microsoft Visual Studio Community 2022 (64-bit) - Current) `Test Explorer` still only displays the test methods and not the four entries mentioned.

#### Questions
* Are there any settings I missed?
* If not, why the four entries did not show separately in Visual Stuido `Test Explorer` and the TRX log?

### Configuration
#### .csproj settings
```
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<TargetFrameworks>net8.0;net472</TargetFrameworks>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<IsPackable>false</IsPackable>
		<OutputType>Library</OutputType>
	</PropertyGroup>

	<!-- Set C# 8.0 for net472 to support Nullable -->
	<PropertyGroup Condition="'$(TargetFramework)' == 'net472'">
		<LangVersion>8.0</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<!--<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />-->
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
		<PackageReference Include="Microsoft.ApplicationInsights" Version="2.22.0" />
		<PackageReference Include="MSTest.Sdk" Version="3.5.2" />
		<PackageReference Include="MSTest.TestAdapter" Version="3.5.2" />
		<PackageReference Include="MSTest.TestFramework" Version="3.5.2" />
		<PackageReference Include="MSTest.Analyzers" Version="3.5.2" />
		<PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="1.3.2" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

</Project>
```
#### UnitTest1.cs

```
namespace mstestfeatures_demo
{

    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using System;

    [TestClass]
    public class UnitTest1
    {

        [AssemblyInitialize]
        public static void AssemblyInit(TestContext context)
        {
            Console.WriteLine("Library init!");
        }

        [ClassInitialize]
        public static void ClassInit(TestContext context)
        {
            Console.WriteLine("Class UnitTest1 init!");
        }

        [ClassCleanup]
        public static void ClassCleanup()
        {
            Console.WriteLine("Class UnitTest1 do cleaning!");
            throw new Exception("Class UnitTest1 Cleanup failed.");
        }

        [TestMethod]
        public void TestMethod1()
        {
            Console.WriteLine("This test method1");
        }

        [TestMethod]
        public void TestMethod2()
        {
            Console.WriteLine("This test method2");
        }
    }
}
```

#### Result
![image](https://github.com/user-attachments/assets/25d59683-3e27-40e0-98c7-f19ac3891273)
![image](https://github.com/user-attachments/assets/42c9865c-6030-49cf-99b8-9b0c857a8152)

##### TRX
```
D:\A_Dev\Csharp\mstests\mstestfeatures_demo\bin\Debug\net472>dotnet test  mstestfeatures_demo.dll --logger "trx;LogFilePrefix=testResults"
VSTest version 17.11.0 (x64)

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed TestMethod2 [< 1 ms]
  Error Message:
   Class Cleanup method UnitTest1.ClassCleanup failed. Error Message: System.Exception: Class UnitTest1 Cleanup failed.. Stack Trace:    at mstestfeatures_demo.UnitTest1.ClassCleanup() in D:\A_Dev\Csharp\mstests\mstestfeatures_demo\UnitTest1.cs:line 27

  Stack Trace:
     at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestClassInfo.ExecuteClassCleanup() in /_/src/Adapter/MSTest.TestAdapter/Execution/TestClassInfo.cs:line 541
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.UnitTestRunner.RunRequiredCleanups(ITestContext testContext, TestMethodInfo testMethodInfo, TestMethod testMethod, UnitTestResult[] results) in /_/src/Adapter/MSTest.TestAdapter/Execution/UnitTestRunner.cs:line 219
  Standard Output Messages:
 This test method2
 Class UnitTest1 do cleaning!


Results File: D:\A_Dev\Csharp\mstests\mstestfeatures_demo\bin\Debug\net472\TestResults\testResults_net472_20240908130504.trx

Failed!  - Failed:     1, Passed:     1, Skipped:     0, Total:     2, Duration: 272 ms - mstestfeatures_demo.dll (net472)
```
[testResults_net472_20240908130504.trx.txt](https://github.com/user-attachments/files/16920894/testResults_net472_20240908130504.trx.txt)

Please correct me if there are any mistakes or misunderstands on my part.

Appreciate for your kind helps!

**Comment by Evangelink** [comment]
I'll reply on the related issue.

**Comment by Vincezhaoc** [comment]
> I'll reply on the related issue.

Thank you Mr @Evangelink.

Appreciate your help with this issue 😊
