### ISSUE TITLE
UWP/WASDK Tests won't run upgrading to 3.1.1

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/testfx#1726]
## Describe the bug

Was trying to update from `2.2.10` to `3.1.1` for MSTest.TestAdapter/Framework as we're not seeing `Logger.LogMessage`/`TextContext.WriteLine` output appear in Visual Studio (no Output/Additional Output link appears next to test), not sure what's going on there, but figured updating may help.

However, after cleaning our environment and reopening Visual Studio, only some tests are discovered and I saw this in the test log:

```
Could not determine target device configuration. Exception: System.Runtime.InteropServices.COMException (0x80020009): The method or operation is not implemented.
   at EnvDTE.Property.get_Value()
   at Microsoft.VisualStudio.TestWindow.ShellServices.ProjectDataImpl.<GetRemoteMachineAddressAsync>d__36.MoveNext()
========== Starting test discovery ==========
========== Test discovery finished: 44 Tests found in 4.8 sec ==========
Could not determine target device configuration. Exception: System.Runtime.InteropServices.COMException (0x80020009): The method or operation is not implemented.
   at EnvDTE.Property.get_Value()
   at Microsoft.VisualStudio.TestWindow.ShellServices.ProjectDataImpl.<GetRemoteMachineAddressAsync>d__36.MoveNext()
Could not determine target device configuration. Exception: System.Runtime.InteropServices.COMException (0x80020009): The method or operation is not implemented.
   at EnvDTE.Property.get_Value()
   at Microsoft.VisualStudio.TestWindow.ShellServices.ProjectDataImpl.<GetRemoteMachineAddressAsync>d__36.MoveNext()
Building Test Projects
Aborting test run due to build failures. Please see the build output for more details.
Building Test Projects
Starting test discovery for requested test run
========== Starting test discovery ==========
An exception occurred while test discoverer 'MSTestDiscoverer' was loading tests. Exception: Method not found: 'Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.MSTestAdapterSettings Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.MSTestSettingsProvider.get_Settings()'.
No test is available in entrypoint\CommunityToolkit.Tests.Uwp.exe. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
========== Test discovery finished: 0 Tests found in 21.5 sec ==========
========== Starting test run ==========
========== Test run finished: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in < 1 ms ==========
```

Using VS 2022 17.6.5. 
WASDK 1.3.230331000 and UWP 
TFMS: net6.0-windows10.0.19041.0/uap10.0.17763

## Steps To Reproduce

1. Fully clone: https://github.com/CommunityToolkit/Labs-Windows (it has a submodule)
2. Update following files in the `tooling` directory to latest version of MSTest:
![image](https://github.com/microsoft/testfx/assets/24302614/f77f2be0-95bf-43c8-8eef-5416f825d4ec)
3. Try and run tests.

## Expected behavior
All tests discovered and tests run

## Actual behavior
Tests don't run/Not all discovered

![image](https://github.com/microsoft/testfx/assets/24302614/f0893b38-61e4-4797-9e41-cbd8a622dd42)

You can see none of our source generated tests are even listed after a build (works _ok_ on 2.2.10 after initial build):

![image](https://github.com/microsoft/testfx/assets/24302614/e46598e2-daf0-4786-aff7-458b1eaad877)

**Comment by AnalogFeelings** [comment]
Same here.

**Comment by Evangelink** [comment]
Hi @michael-hawker,

For the various
```cmd
Could not determine target device configuration. Exception: System.Runtime.InteropServices.COMException (0x80020009): The method or operation is not implemented.
   at EnvDTE.Property.get_Value()
   at Microsoft.VisualStudio.TestWindow.ShellServices.ProjectDataImpl.<GetRemoteMachineAddressAsync>d__36.MoveNext()
```

showing in the output, please open an issue on developer community this is linked to some bug in Test Explorer and it's not handled by us.

For the other part of the problem. you haven't given me much information as to what is missing... I have done a build, open the sln on VS and I see 6 tests under `ExampleCanbasLayoutTestClass` which seems to be 3 more than you. I can also run them correctly.
![image](https://github.com/microsoft/testfx/assets/11340282/4da9c9ca-b518-4e7d-967d-b07b817d5950)

**Comment by ErikApption** [comment]
I'm seeing same issue here on a non UWP project

**Comment by sonnemaf** [comment]
I also have this problem. I hope it will get fixed. 

The Test output windows shows that there is an exception in the `Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.MSTestSettingsProvider.get_Settings()`.

```
========== Starting test run ==========
========== Test run finished: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in < 1 ms ==========
========== Starting test run ==========
========== Test run finished: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in < 1 ms ==========
Starting test discovery for requested test run
========== Starting test discovery ==========
An exception occurred while test discoverer 'MSTestDiscoverer' was loading tests. Exception: Method not found: 'Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.MSTestAdapterSettings Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.MSTestSettingsProvider.get_Settings()'.
No test is available in entrypoint\UnitTestProject1.exe. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
========== Test discovery finished: 0 Tests found in 820 ms ==========
========== Starting test run ==========
========== Test run finished: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in < 1 ms ==========
Starting test discovery for requested test run
========== Starting test discovery ==========
========== Test discovery finished: 1 Tests found in 2.6 sec ==========
========== Starting test run ==========
========== Test run finished: 1 Tests (1 Passed, 0 Failed, 0 Skipped) run in 125 ms ==========
Starting test discovery for requested test run
========== Starting test discovery ==========
An exception occurred while test discoverer 'MSTestDiscoverer' was loading tests. Exception: Method not found: 'Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.MSTestAdapterSettings Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.MSTestSettingsProvider.get_Settings()'.
No test is available in entrypoint\UnitTestProject1.exe. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
========== Test discovery finished: 0 Tests found in 2.3 sec ==========
========== Starting test run ==========
========== Test run finished: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in < 1 ms ==========
```

**Comment by juanmalm** [comment]
Same here

**Comment by dotMorten** [comment]
Me too
