### ISSUE TITLE
Retry extension gives error

### ISSUE THREAD

**Issue by nohwnd** [microsoft/testfx#2189]
The retry extensions gives errors when running. We get: This program is thought to be unreachable. File=’/_/src/Microsoft.Testing.Extensions.Retry/RetryOrchestrator.cs’ Line 73.

https://devblogs.microsoft.com/dotnet/introducing-ms-test-runner/#comment-20352

[AB#1948289](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1948289)

**Comment by zelda1link3** [comment]
Besides it links intern to: 
https://raw.githubusercontent.com/microsoft/testanywhere/0c57bfaed0eceb88df5067f 45c454685b077e3eb/src/Microsoft.Testing.Extensions.Retry/RetryOrchestrator.cs

I suspect this is a private repo and i don't think this should stil be in here.

also here is the complete stacktrace:


Unhandled exception. System.InvalidOperationException: This program location is thought to be unreachable. File='/_/src/Microsoft.Testing.Extensions.Retry/RetryOrchestrator.cs' Line=73
   at Microsoft.Testing.Extensions.Policy.RetryOrchestrator.OrchestrateTestHostExecutionAsync() in /_/src/Microsoft.Testing.Extensions.Retry/RetryOrchestrator.cs:line 95
   at Microsoft.Testing.Platform.Hosts.TestHostOrchestratorHost.RunAsync() in /_/src/Platform/Microsoft.Testing.Platform/Hosts/TestHostOchestratorHost.cs:line 30
   at Microsoft.Testing.Platform.Builder.TestApplication.RunAsync() in /_/src/Platform/Microsoft.Testing.Platform/Builder/TestApplication.cs:line 237
   at TestingPlatformEntryPoint.Main(String[] args) in c:\Test\obj\Release\net6.0\TestPlatformEntryPoint.cs:line 20
   at TestingPlatformEntryPoint.<Main>(String[] args)

**Comment by zelda1link3** [comment]
I fixed it for now.
If i add the argument -retry-failled-tests 3 it does not work but with --retry-failed-tests 3 it works.

**Comment by Evangelink** [comment]
Hi @zelda1link3, I confirm that there is an issue with the handling of `-retry-failed-tests` while `--retry-failed-tests` works properly. We will investigate and provide a fix asap.

**Comment by Evangelink** [comment]
Reopening to track the release

**Comment by Evangelink** [comment]
Sorry for the change of mind. I'll use the milestone :)
