### ISSUE TITLE
An exception occurred while invoking executor executor://mstestadapter/v2. System.IO.DirectoryNotFoundException

### ISSUE THREAD

**Issue by cbersch** [microsoft/testfx#2219]
## Describe the bug
Our Azure DevOps pipeline, which runs tests from 60 assemblies in parallel via `dotnet test`, randomly fails with the exception
```
An exception occurred while invoking executor executor://mstestadapter/v2. System.IO.DirectoryNotFoundException: Could not find a part of the path 'F:\agent\_work\1\s\TestResults\Deploy_user 20240131T155218[1]\In\BLDSRV01'.
```
The .NET8 projects reference packages
- `MSTest.TestAdapter` 3.1.1
- `MSTest.TestFramework` 3.1.1
- `Microsoft.NET.Test.Sdk` 17.8.0

## Steps To Reproduce
Not really, but the Task runs the following `dotnet test` command:
```
dotnet test ./MySolution.sln --no-build --no-restore --configuration=Release --logger=trx --results-directory=TestResults --settings=.runsettings --collect="Code Coverage;Format=cobertura" --diag=TestResults\dotnet-test.diag
```
## Expected behavior
The tests are executed and `dotnet test` exits with code 0

## Actual behavior
The tests are not executed and `dotnet test` exits with code 1

## Additional context
The relevant part from the `diag` file
```
TpTrace Information: 0 : 23220, 4, 2024/01/31, 15:52:18.408, 2190101548319, testhost.dll, MSTest - MSTestDiscoverer: Found 8 tests from source F:\agent\_work\1\s\_Build\Release\Assemblies\ipipe.DataMapping.Test\ipipe.DataMapping.Test.dll
TpTrace Verbose: 0 : 23220, 9, 2024/01/31, 15:52:18.512, 2190102589919, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:55794 localEndPoint: [::ffff:127.0.0.1]:55853
TpTrace Error: 0 : 23220, 4, 2024/01/31, 15:52:19.234, 2190109808184, testhost.dll, BaseRunTests.RunTestInternalWithExecutors: An exception occurred while invoking executor executor://mstestadapter/v2. System.IO.DirectoryNotFoundException: Could not find a part of the path 'F:\agent\_work\1\s\TestResults\Deploy_user 20240131T155218[1]\In\BLDSRV01'.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Utilities.FileUtility.CreateDirectoryIfNotExists(String directory) in /_/src/Adapter/MSTestAdapter.PlatformServices/Utilities/FileUtility.cs:line 32
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Utilities.DeploymentUtilityBase.CreateDeploymentDirectories(IRunContext runContext) in /_/src/Adapter/MSTestAdapter.PlatformServices/Utilities/DeploymentUtilityBase.cs:line 73
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.TestDeployment.Deploy(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle) in /_/src/Adapter/MSTestAdapter.PlatformServices/Services/TestDeployment.cs:line 147
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestExecutionManager.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle, TestRunCancellationToken cancellationToken) in /_/src/Adapter/MSTest.TestAdapter/Execution/TestExecutionManager.cs:line 126
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.MSTestExecutor.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle) in /_/src/Adapter/MSTest.TestAdapter/MSTestExecutor.cs:line 107
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionDecorators.SerialTestRunDecorator.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle) in /_/src/Microsoft.TestPlatform.Common/ExtensionDecorators/SerialTestRunDecorator.cs:line 57
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.RunTestsWithSources.InvokeExecutor(LazyExtension`2 executor, Tuple`2 executorUriExtensionTuple, RunContext runContext, IFrameworkHandle frameworkHandle) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Execution/RunTestsWithSources.cs:line 115
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestInternalWithExecutors(IEnumerable`1 executorUriExtensionMap, Int64 totalTests) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Execution/BaseRunTests.cs:line 466.
TpTrace Error: 0 : 23220, 4, 2024/01/31, 15:52:19.235, 2190109811872, testhost.dll, An exception occurred while invoking executor 'executor://mstestadapter/v2': Could not find a part of the path 'F:\agent\_work\1\s\TestResults\Deploy_user 20240131T155218[1]\In\BLDSRV01'.
Stack trace:
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Utilities.FileUtility.CreateDirectoryIfNotExists(String directory) in /_/src/Adapter/MSTestAdapter.PlatformServices/Utilities/FileUtility.cs:line 32
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Utilities.DeploymentUtilityBase.CreateDeploymentDirectories(IRunContext runContext) in /_/src/Adapter/MSTestAdapter.PlatformServices/Utilities/DeploymentUtilityBase.cs:line 73
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.TestDeployment.Deploy(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle) in /_/src/Adapter/MSTestAdapter.PlatformServices/Services/TestDeployment.cs:line 147
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestExecutionManager.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle, TestRunCancellationToken cancellationToken) in /_/src/Adapter/MSTest.TestAdapter/Execution/TestExecutionManager.cs:line 126
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.MSTestExecutor.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle) in /_/src/Adapter/MSTest.TestAdapter/MSTestExecutor.cs:line 107
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionDecorators.SerialTestRunDecorator.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle) in /_/src/Microsoft.TestPlatform.Common/ExtensionDecorators/SerialTestRunDecorator.cs:line 57
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.RunTestsWithSources.InvokeExecutor(LazyExtension`2 executor, Tuple`2 executorUriExtensionTuple, RunContext runContext, IFrameworkHandle frameworkHandle) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Execution/RunTestsWithSources.cs:line 115
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestInternalWithExecutors(IEnumerable`1 executorUriExtensionMap, Int64 totalTests) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Execution/BaseRunTests.cs:line 466
```

[AB#1957774](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1957774)

**Comment by Evangelink** [comment]
Thanks for reporting the issue @cbersch. I will investigate soon.

**Comment by Evangelink** [comment]
Looking online it seems that `DirectoryNotFoundException` can be thrown for unmapped drive. Are you by chance changing the directory through some runsettings?

For the other part of the bug, where you expect the tests to stop, I would create an issue on https://github.com/microsoft/vstest because that's the platform responsibility as we are not doing any specific handling of the exception.

**Comment by Evangelink** [comment]
@cbersch @msedi Could you confirm that `F:` is a mapped network drive?

**Comment by msedi** [comment]
@Evangelink:

> Could you confirm that F: is a mapped network drive?

No, it's a normal drive.

**Comment by Evangelink** [comment]
Is this happening regularly or is it a rare error? I'll check out what are the other reasons that could lead to this exception.

**Comment by cbersch** [comment]
This happens on a quite regular base, currently approximately one of five pipeline runs fails with this error.

**Comment by Evangelink** [comment]
I am investigating the cases that can lead to the exception being thrown. So far, my best suggestion would be do put some retry mechanism around the directory creation but that seems a poorman solution without better understanding of why it's failing.

**Comment by cbersch** [comment]
Couldn't it also be a problem when starting the test hosts?
Here, the problematic path contains `20240131T155218[1]`. Who decides, that the path needs a `[1]`? 

Searching through all `diag` files of the pipeline run, I have four `diag`-files, which contain the very same path, which also lead to the exception. The names of the files are 

* `dotnet-test.host.24-01-31_15-52-03_01021_5.diag`
* `dotnet-test.host.24-01-31_15-52-03_56239_5.diag`
* `dotnet-test.host.24-01-31_15-52-03_56864_5.diag`
* `dotnet-test.host.24-01-31_15-52-03_57364_5.diag`

The third one is the one which contains the exception.
The second file contains the following lines:
```
TpTrace Verbose: 0 : 38124, 12, 2024/01/31, 15:52:18.559, 2190103058689, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:55792 localEndPoint: [::ffff:127.0.0.1]:55850
TpTrace Information: 0 : 38124, 4, 2024/01/31, 15:52:18.734, 2190104806978, testhost.dll, Deleting deployment directory F:\agent\_work\1\s\TestResults\Deploy_user 20240131T155218[1]
TpTrace Information: 0 : 38124, 4, 2024/01/31, 15:52:18.736, 2190104822338, testhost.dll, Deleted deployment directory F:\agent\_work\1\s\TestResults\Deploy_user 20240131T155218[1]
TpTrace Verbose: 0 : 38124, 4, 2024/01/31, 15:52:18.736, 2190104824584, testhost.dll, BaseRunTests.RunTestInternalWithExecutors: Completed running tests for executor://MSTestAdapter/v2
```

So one testhost deletes the directory which another one still needs to access.

**Comment by Evangelink** [comment]
Asked runtime https://github.com/dotnet/runtime/issues/97980

**Comment by cbersch** [comment]
@Evangelink Have you looked at the code where the directory names are created, in which the temporary data is saved?

Looks to me, like multiple test hosts (I'm not sure if this is the correct naming), run different assemblies with the same temporary directory. And the first to finish, deletes the directory which isn't available anymore for the other, still running ones.

**Comment by Evangelink** [comment]
> directory names are created, in which the temporary data is saved?

MSTest uses info provided by VSTest, they are the regular directories.

> And the first to finish, deletes the directory which isn't available anymore for the other, still running ones.

Each testhost has its own folder. Also if the issue was that the folder gets deleted when we are still doing some processing we wouldn't get the error you described in your OP (which clearly state there is a problem when doing call to Directory.Create).

**Comment by cbersch** [comment]
> > And the first to finish, deletes the directory which isn't available anymore for the other, still running ones.
> 
> Each testhost has its own folder. 

That is not the case in this example. Four testhosts have the same folder `F:\agent\_work\1\s\TestResults\Deploy_user 20240131T155218[1]`.

**Comment by Evangelink** [comment]
4 testhosts -> have you looked at the logs or is it because you have 4 test assemblies?

**Comment by cbersch** [comment]
> 4 testhosts -> have you looked at the logs or is it because you have 4 test assemblies?

I looked at the `diag`-files, see https://github.com/microsoft/testfx/issues/2219#issuecomment-1921186084

**Comment by Evangelink** [comment]
@cbersch Would you be willing to test out some preview packages to test if a retry around the creation could help?

**Comment by cbersch** [comment]
> @cbersch Would you be willing to test out some preview packages to test if a retry around the creation could help?

@Evangelink yes, please.

What about changing the way the names of the deployment directories are generated? 
I assume, that's the actual problem.

**Comment by Evangelink** [comment]
> @Evangelink yes, please.

Awesome, let me prepare something.

> What about changing the way the names of the deployment directories are generated?
I assume, that's the actual problem.

This is all handled by vstest. @nohwnd Do you think this could be linked to the issue described here?
I have doubts this is related, at least for the issue you raised in the first comment. The issue clearly complains about failure when calling create dir not about some dir not existing.

**Comment by cbersch** [comment]
It might be related to vstest issue https://github.com/microsoft/vstest/issues/2372
The error is basically the same: One test host deletes the deployment directory while another one must access it

**Comment by Evangelink** [comment]
The error you posted above

```text
TpTrace Error: 0 : 23220, 4, 2024/01/31, 15:52:19.234, 2190109808184, testhost.dll, BaseRunTests.RunTestInternalWithExecutors: An exception occurred while invoking executor executor://mstestadapter/v2. System.IO.DirectoryNotFoundException: Could not find a part of the path 'F:\agent\_work\1\s\TestResults\Deploy_user 20240131T155218[1]\In\BLDSRV01'.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Utilities.FileUtility.CreateDirectoryIfNotExists(String directory) in /_/src/Adapter/MSTestAdapter.PlatformServices/Utilities/FileUtility.cs:line 32
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Utilities.DeploymentUtilityBase.CreateDeploymentDirectories(IRunContext runContext) in /_/src/Adapter/MSTestAdapter.PlatformServices/Utilities/DeploymentUtilityBase.cs:line 73
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.TestDeployment.Deploy(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle) in /_/src/Adapter/MSTestAdapter.PlatformServices/Services/TestDeployment.cs:line 147
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestExecutionManager.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle, TestRunCancellationToken cancellationToken) in /_/src/Adapter/MSTest.TestAdapter/Execution/TestExecutionManager.cs:line 126
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.MSTestExecutor.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle) in /_/src/Adapter/MSTest.TestAdapter/MSTestExecutor.cs:line 107
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionDecorators.SerialTestRunDecorator.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle) in /_/src/Microsoft.TestPlatform.Common/ExtensionDecorators/SerialTestRunDecorator.cs:line 57
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.RunTestsWithSources.InvokeExecutor(LazyExtension`2 executor, Tuple`2 executorUriExtensionTuple, RunContext runContext, IFrameworkHandle frameworkHandle) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Execution/RunTestsWithSources.cs:line 115
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestInternalWithExecutors(IEnumerable`1 executorUriExtensionMap, Int64 totalTests) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Execution/BaseRunTests.cs:line 466.
```

really is different to me. It's not complaining about accessing something that doesn't exist or is in use.

**Comment by cbersch** [comment]
This error message itself not, but the fact, that this very same directory is deleted by another testhost at the same time, which is, what the other log snippet tells

```
TpTrace Verbose: 0 : 38124, 12, 2024/01/31, 15:52:18.559, 2190103058689, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:55792 localEndPoint: [::ffff:127.0.0.1]:55850 TpTrace Information: 0 : 38124, 4, 2024/01/31, 15:52:18.734, 2190104806978, testhost.dll, Deleting deployment directory F:\agent\_work\1\s\TestResults\Deploy_user 20240131T155218[1] TpTrace Information: 0 : 38124, 4, 2024/01/31, 15:52:18.736, 2190104822338, testhost.dll, Deleted deployment directory F:\agent\_work\1\s\TestResults\Deploy_user 20240131T155218[1] TpTrace Verbose: 0 : 38124, 4, 2024/01/31, 15:52:18.736, 2190104824584, testhost.dll, BaseRunTests.RunTestInternalWithExecutors: Completed running tests for executor://MSTestAdapter/v2 
```
Its the combination of both logs that show a race condition between the hosts

**Comment by Evangelink** [comment]
Oh right indeed. So that's a bug on VSTest side, right?

**Comment by nohwnd** [comment]
> The check for an existing directory and the possibly addition of `[1]` isn't safe enough.
> To avoid race conditions more reliably, the line should be
> 
> ```
> string dateTimeSuffix = DateTime.Now.ToString("yyyyMMddTHHmmssfff", DateTimeFormatInfo.InvariantInfo);
> ```
> 
> which adds the microseconds as part of the directory name.

This is a possibility, but on .NET Framework both DateTime.Now and DateTime.UtcNow don't use high precision system clock api, and so their precision is about 15ms, so you are likely to hit the same issue, but maybe less frequently.  So if the change should be made it should be: 

```cs
DateTime.UtcNow.ToLocalTime().ToString("yyyyMMddTHHmmssfffffff")
```

**Comment by nohwnd** [comment]
> Oh right indeed. So that's a bug on VSTest side, right?

Imho no, I think it is a bug in mstest deployment, vstest does not know that you will try to deploy to the same folder.  

Looks to me that the check for existing folder in deployer is good, but might not be as random as the author of that code thought when the check is happening at the same time from two testhosts.

https://github.com/microsoft/testfx/issues/2219#issuecomment-1936406786

Maybe a combination of the more precise timestamp, or the per-second precision + short random ID (https://github.com/microsoft/vstest/blob/main/test/Microsoft.TestPlatform.TestUtilities/RandomId.cs)  might be better.

**Comment by nohwnd** [comment]
re-iterating what was said above: race condition is between checking if the folder exists, and it's creation. Where all testhosts start at the same time, and end up deploying to the same folder: 

[testfx/src/Adapter/MSTestAdapter.PlatformServices/Utilities/FileUtility.cs at main · microsoft/testfx (github.com)](https://github.com/microsoft/testfx/blob/main/src/Adapter/MSTestAdapter.PlatformServices/Utilities/FileUtility.cs#L66-L76) in code the race is here between the exists  and creating the name.

 and 68, where we create.  [testfx/src/Adapter/MSTestAdapter.PlatformServices/Utilities/DeploymentUtilityBase.cs at main · microsoft/testfx (github.com)](https://github.com/microsoft/testfx/blob/main/src/Adapter/MSTestAdapter.PlatformServices/Utilities/DeploymentUtilityBase.cs#L64-L68)

**Comment by cbersch** [comment]
> Maybe a combination of the more precise timestamp, or the per-second precision + short random ID (https://github.com/microsoft/vstest/blob/main/test/Microsoft.TestPlatform.TestUtilities/RandomId.cs) might be better.

When using the per-second precision plus a short random ID, then the logic for appending [<n>] could also be dropped.

**Comment by MarcoRossignoli** [comment]
I think we can append the current PID and we will have unique path, PID till process is alive is unique and MSTest self create/destroy it.
