### ISSUE TITLE
Retry extension exception on osx.13-arm64

### ISSUE THREAD

**Issue by bmcclory** [microsoft/testfx#2297]
## Describe the bug

`Microsoft.Testing.Extensions.Retry` (1.0.0) does not working on Mac (ARM) runtime. Runtime exception:

```
Microsoft(R) Testing Platform Execution Command Line Tool
Version: 1.0.0+00333e15d (UTC 2024/01/24)
RuntimeInformation: osx.13-arm64 - .NET 7.0.12
Copyright(c) Microsoft Corporation.  All rights reserved.
Unhandled exception. System.ArgumentOutOfRangeException: The path '/var/folders/jd/70dmjhl15_94kvft_dz552ph0000gq/T/RetryFailedTestsOrchestrator_6c71eeb55820467f8cf1bc78248b762d/.pipe' is of an invalid length for use with domain sockets on this platform.  The length must be between 1 and 104 characters, inclusive. (Parameter 'path')
Actual value was /var/folders/jd/70dmjhl15_94kvft_dz552ph0000gq/T/RetryFailedTestsOrchestrator_6c71eeb55820467f8cf1bc78248b762d/.pipe.
   at System.Net.Sockets.UnixDomainSocketEndPoint..ctor(String path, String boundFileName)
   at System.IO.Pipes.NamedPipeServerStream.SharedServer..ctor(String path, Int32 maxCount)
   at System.IO.Pipes.NamedPipeServerStream.SharedServer.Get(String path, Int32 maxCount)
   at System.IO.Pipes.NamedPipeServerStream.Create(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, HandleInheritability inheritability)
   at System.IO.Pipes.NamedPipeServerStream..ctor(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances)
   at Microsoft.Testing.Platform.IPC.NamedPipeServer..ctor(PipeNameDescription pipeNameDescription, Func`2 callback, IEnvironment environment, ILogger logger, ITask task, Int32 maxNumberOfServerInstances, CancellationToken cancellationToken) in /_/src/Platform/Microsoft.Testing.Platform/IPC/NamedPipeServer.cs:line 66
   at Microsoft.Testing.Platform.IPC.NamedPipeServer..ctor(PipeNameDescription pipeNameDescription, Func`2 callback, IEnvironment environment, ILogger logger, ITask task, CancellationToken cancellationToken) in /_/src/Platform/Microsoft.Testing.Platform/IPC/NamedPipeServer.cs:line 52
   at Microsoft.Testing.Extensions.Policy.RetryFailedTestsPipeServer..ctor(IServiceProvider serviceProvider, String[] failedTests) in /_/src/Microsoft.Testing.Extensions.Retry/RetryFailedTestsPipeServer.cs:line 22
   at Microsoft.Testing.Extensions.Policy.RetryOrchestrator.OrchestrateTestHostExecutionAsync() in /_/src/Microsoft.Testing.Extensions.Retry/RetryOrchestrator.cs:line 136
   at Microsoft.Testing.Platform.Hosts.TestHostOrchestratorHost.RunAsync() in /_/src/Platform/Microsoft.Testing.Platform/Hosts/TestHostOchestratorHost.cs:line 30
   at Microsoft.Testing.Platform.Builder.TestApplication.RunAsync() in /_/src/Platform/Microsoft.Testing.Platform/Builder/TestApplication.cs:line 237
   at TestingPlatformEntryPoint.Main(String[] args) in /Users/bmcclory/IDX.AutomatedTests/source/obj/Debug/net7.0/TestPlatformEntryPoint.cs:line 19
   at TestingPlatformEntryPoint.<Main>(String[] args)
```
## Steps To Reproduce

Run test project (either as published executable or with `dotnet run`) with `--retry-failed-tests 3` option.

**Comment by MarcoRossignoli** [comment]
Thanks for reporting this, I see similar issue in runtime repo https://github.com/dotnet/runtime/issues/79503

We need to shorter down a bit the pipe name.

**Comment by Evangelink** [comment]
@bmcclory MSTest 3.2.1 was just released.
