### ISSUE TITLE
dependencies of MSTest Adapter ?

### ISSUE THREAD

**Issue by fforjan** [microsoft/testfx#2489]
## Describe the bug

<img width="1049" alt="image" src="https://github.com/microsoft/testfx/assets/601810/517c6689-14dd-448c-bad6-bab2ec62a620">

With an empty projects, it seems now that the test adapter brings extra dependencies like newtonsoft and application insights.
Our own test projects may bring those dependencies too ?

We are seeing some issues about wrong dependencies when switching from MSTest 3.1.1 to 3.2.2 and we were wondering if that would be the root cause - we were not able to reproduce the issues, just pipeline failures.

I understand your idea of bringing telemetry but it seems that it bring too many dependencies and we were wondering if you should remove the telemetry test extension from the main package ?

## Steps To Reproduce

Create new test project via dot new mstest
update to mstest 3.2.2

## Expected behavior

No extra dll like newtonsoft of app insight

**Comment by fforjan** [comment]
@nohwnd 
We are still slowing investigating the issue, some of our tests works were perfectly with mstest 3.1.1 and are now failing with mstest 3.2.2 but only on our pipeline, we cannot reproduce (yet) on developer machine
Error Message:
```
Initialization method OurTests.Initialize threw exception. System.IO.FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=7.0.0.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040).
TestCleanup method OurTest.Cleanup threw exception. System.NullReferenceException: Object reference not set to an instance of an object..
```
StackTrace:
```
at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
at System.Reflection.RuntimeMethodInfo.GetParameters()
at Castle.DynamicProxy.Generators.MethodSignatureComparer.GetHashCode(MethodInfo obj)
at System.Linq.Set`1.InternalGetHashCode(TElement value)
at System.Linq.Set`1.Find(TElement value, Boolean add)
at System.Linq.Enumerable.<DistinctIterator>d__64`1.MoveNext()
at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
at Castle.DynamicProxy.Generators.MethodFinder.GetAllInstanceMethods(Type type, BindingFlags flags)
at Castle.DynamicProxy.Contributors.MembersCollector.<CollectMembersToProxy>g__CollectMethods|7_2(<>c__DisplayClass7_0& )
at Castle.DynamicProxy.Contributors.MembersCollector.CollectMembersToProxy(IProxyGenerationHook hook, IMembersCollectorSink sink)
at Castle.DynamicProxy.Contributors.CompositeTypeContributor.CollectElementsToProxy(IProxyGenerationHook hook, MetaType model)
at Castle.DynamicProxy.Generators.BaseInterfaceProxyGenerator.GenerateType(String typeName, INamingScope namingScope)
at Castle.Core.Internal.SynchronizedDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
at Castle.DynamicProxy.Generators.BaseProxyGenerator.GetProxyType()
at Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyWithoutTarget(Type interfaceToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options, IInterceptor[] interceptors)
[at Moq.Mock`1.InitializeInstance() in /_/src/Moq/Mock`1.cs:line 502]
[at Moq.Mock`1.OnGetObject() in /_/src/Moq/Mock`1.cs:line 519]
[at Moq.Mock`1.get_Object() in /_/src/Moq/Mock`1.cs:line 453]
[at OurTests.HelperMocks.CreateLogSession(ContainerSettings containerSettings) 
[at OurTests.HelperMocks.CreateTestSetup() in 
[at OurTests.Initialize() in 
TestCleanup Stack Trace
[at OurTests.Cleanup() in OurTests.cs:line 106]
```

Different error:
```
OurTests.WhenCreatingEventSinkAndSinkEmittedLogsShouldProduceLogs threw exception:
System.IO.FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=7.0.0.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

Stack trace:
```
at OurTests.WhenCreatingEventSinkAndSinkEmittedLogsShouldProduceLogs()
```

Our pipeline (on prem agent we managed ourselves) have been updated to VS 2022 17.9.0, we are using Microsoft.NET.Test.Sdk in version 17.9.0 and pipeline is using also D:\BldSrc\_tool\VsTest\17.9.0\x64\tools\net462\Common7\IDE\Extensions\TestPlatform\vstest.console.exe

**Comment by fforjan** [comment]
@nohwnd  I think the issue is on our side, the current idea is this
We are using DeploymentItem and some of those items are deploying individual dll.
In previous version of MStest 3.1.1, some of dependencies were provided by MSTest (like System.Reflection.Metadata).
When we are upgrading to MSTest 3.2.2, the dependencies are either invalid or missing.

I think we need to rethink our DeploymentItem strategy when deploying dll.

**Comment by MarcoRossignoli** [comment]
> We are using DeploymentItem and some of those items are deploying individual dll.

@fforjan can you explain me why you need `DeploymentItem`  and you cannot use simple post build?

**Comment by fforjan** [comment]
@MarcoRossignoli  that was in our design 10 years ago and we have not review this in a long time. 
One thing it seems we are using it - not in the context of this issue - is to deploy native dlls it is the only way we found how to deploy native dlls for the specific test.
But I could not remember/do not know why we started with DeploymentEnabled in our config file.
Sometimes it seems people were having an issue, didn't find a root cause but discovered that enabling deployment was solving the issue....

Give me a  couple of days to do some analysis  - I shoudl be able to run on pipeline without deployment enabled and see where are the failures.

**Comment by MarcoRossignoli** [comment]
> (yes desktop application context, we load from the file system :))

Windows form controls? Isn't easy inject a custom `IFileSystem` and make it testable?

**Comment by fforjan** [comment]
@MarcoRossignoli  We have done that in our recent iterations, but we have some old codes still waiting.
To give you an idea :
![image](https://github.com/microsoft/testfx/assets/601810/b6556d15-b469-4eda-953b-115242cf6ede)
We have a bit of work to check if it is really needed or not ...

**Comment by fforjan** [comment]
> I wonder how slow is all this too how many copy...and if only one it's like a foreach->File.Copy->Execute
MSTEst in our case is not only use for unit tests but also integration tests were we run most of the products and goes to the file system.
Overall, yes for unit test the deployment item are slowing done the process, but for integration tests, the time lost is negligeable compare to those tests and I would think most of the integration tests requires the deployment item as the moment

**Comment by MarcoRossignoli** [comment]
got it thanks...let us know if you fix your issue and if you want give it a try to the new test runner. That's the path we would like to take.

**Comment by fforjan** [comment]
@kasajian ping !

**Comment by fforjan** [comment]
@MarcoRossignoli I will be closing this issue as it is more likely due to setup of unit tests on our side.

**Comment by kasajian** [comment]
It'd be good to have the Microsoft Program Manager who is deciding to deprecate the [DeploymentItem] attribute from Visual Studio to weigh-in on this decision.   If that's at all possible to do, maybe we can have them participate in this discussion.

**Comment by MarcoRossignoli** [comment]
> It'd be good to have the Microsoft Program Manager who is deciding to deprecate the [DeploymentItem] attribute from Visual Studio to weigh-in on this decision. If that's at all possible to do, maybe we can have them participate in this discussion.

@kasajian sorry for the confusion but I didn't say that we will deprecate it, it was more "I'd like" because the implementation is adding some perf penalties (I/O) also when a suite doesn't use it.

But there's no plan to deprecate it so don't worry.
