### ISSUE TITLE
Microsoft.TestPlatform (17.4.0-preview-20220726-02) not working

### ISSUE THREAD

**Issue by alexanderjung-sdxag** [microsoft/testfx#3255]
## Description
Since updating to the latest version of Microsoft.TestPlatform, unittests don't run anymore in Azure DevOps pipelines. 
It seems as if there are some assembly reference mismatches, and test attributes are no longer recognized.

https://www.nuget.org/packages/Microsoft.TestPlatform 
17.4.0-preview-20220726-02	<== error
17.2.0 (latestStable) <== works
17.4.0-preview-20220707-01	<== works

## Steps to reproduce
Build pipeline step:
```
- task: VisualStudioTestPlatformInstaller@1
  displayName: 'Install Test Platform'
```

## Expected behavior
Tests running fine.

## Actual behavior

example 1:
```
  Failed TestFileArchiveOptions
  Error Message:
   Unable to set TestContext property for the class xxx.FileArchiveTest. Error: System.ArgumentException: Object of type 'Microsoft.VisualStudio.TestPlatform.MSTestFramework.TestContextImplementation' cannot be converted to type 'Microsoft.VisualStudio.TestTools.UnitTesting.TestContext'..
  Stack Trace:
      at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at Microsoft.VisualStudio.TestPlatform.MSTestFramework.TestMethodRunner.SetTestContext()
```
The test class in question is fine:
```
    [TestClass]
    public class FileArchiveTest 
    {
        public TestContext TestContext { get; set; }
```

example 2:
```
  Failed RunActivity_SingleActivityWithBaggage_BaggageIsSet
  Error Message:
   Method xxx.ClassInitialize has wrong signature. The method must be static, public, does not return a value and should take a single parameter of type TestContext.
```
the method looks fine:
```
        [ClassInitialize]
        public static void ClassInitialize(TestContext context)
```
example 3:
```
  Failed TarjanTest5 [1 ms]
  Error Message:
   Test method xxx.TopoSortTest.TarjanTest5 threw exception: 
System.InvalidOperationException: Graph is not complete. Missing node 'v7' in adjacency list. Check if node is defined as key in the dictionary.
```
the ExpectedException attibute is not honored:
```
        [TestMethod]
        [ExpectedException(typeof(InvalidOperationException))]
        public void TarjanTest5()
        {
```

## Diagnostic logs

failing output:
```
##[section]Starting: Install Test Platform
==============================================================================
Task         : Visual Studio test platform installer
Description  : Acquire the test platform from nuget.org or the tool cache. Satisfies the ‘vstest’ demand and can be used for running tests and collecting diagnostic data using the Visual Studio Test task.
Version      : 1.151.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/vstest-platform-tool-installer
==============================================================================
Starting VsTest platform tools installer task.
==============================================================================
Looking for the latest pre-release version of the Microsoft.Testplatform.
[command]C:\CI\7\_work\_tasks\VisualStudioTestPlatformInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7111\1.151.3\nuget.exe list packageid:Microsoft.TestPlatform -PreRelease -NonInteractive -Source https://api.nuget.org/v3/index.json
Microsoft.TestPlatform 17.4.0-preview-20220726-02
Found tool in cache: VsTest 17.4.0-preview-20220726-02 x64
VsTest will use the Test Platform package found in C:\CI\7\_work\_tool\VsTest\17.4.0-preview-20220726-02\x64
##[section]Finishing: Install Test Platform
```
working output:
```
##[section]Starting: Install Test Platform
==============================================================================
Task         : Visual Studio test platform installer
Description  : Acquire the test platform from nuget.org or the tool cache. Satisfies the ‘vstest’ demand and can be used for running tests and collecting diagnostic data using the Visual Studio Test task.
Version      : 1.151.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/vstest-platform-tool-installer
==============================================================================
Starting VsTest platform tools installer task.
==============================================================================
Looking for the latest pre-release version of the Microsoft.Testplatform.
[command]C:\CI\1\_work\_tasks\VisualStudioTestPlatformInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7111\1.151.3\nuget.exe list packageid:Microsoft.TestPlatform -PreRelease -NonInteractive -Source https://api.nuget.org/v3/index.json
Microsoft.TestPlatform 17.4.0-preview-20220707-01
Found tool in cache: VsTest 17.4.0-preview-20220707-01 x64
VsTest will use the Test Platform package found in C:\CI\1\_work\_tool\VsTest\17.4.0-preview-20220707-01\x64
##[section]Finishing: Install Test Platform
```

## Environment
Azure Devops pipelines

## Workarouds:
use earlier versions:

```
- task: VisualStudioTestPlatformInstaller@1
  displayName: 'Install Test Platform (latestStable!)'
  inputs:  
    packageFeedSelector: 'nugetOrg'
    versionSelector: 'latestStable'
```
or
```
- task: VisualStudioTestPlatformInstaller@1
  displayName: 'Install Test Platform (pinned version!)'
  inputs:
    packageFeedSelector: 'nugetOrg'
    versionSelector: 'specificVersion'
    testPlatformVersion: '17.4.0-preview-20220707-01'
```

**Comment by nohwnd** [comment]
Moved the issue here, it is problem with MSTest, and possibly some conflict with vstest.

@evangelink please try if you can repro.

**Comment by Evangelink** [comment]
Yes I do repro the issue @nohwnd. As discussed offline yesterday, output is good if I use `dotnet test` or `Test Explorer` but calling `vstest.console.exe` is producing the error. Given that the dll contains a single test, I don't expect to see that many results.

**Comment by nohwnd** [comment]
Ah that was this issue :D

**Comment by riQQ** [comment]
This is just the fastest repro I came up with.

Our actual situation is that we have a *Tests* folder, where we build every test project in a subfolder and then just glob all test DLLs via `**\*.Tests.dll` in the *Tests* folder. Noone noticed that some tests were run multiple times. 

The solution for us was the same as GoAvalon's. We extracted the shared code to a library without any tests, thus avoiding mutliple copies of an assembly with tests ending up in our build output.

> You don't have to use this workaound, but new vstest (17.11) comes with a runsetting that is `-- RunConfiguration.SkipDefaultAdapters=true` which will skip all the built in adapters that ship with VS.

Just for reference, I found the change you mentioned here: microsoft/vstest#5018

**Comment by nohwnd** [comment]
> We extracted the shared code to a library without any tests, thus avoiding mutliple copies of an assembly with tests ending up in our build output.

That is a good solution, I think it is good practice to not mix test project, and test infrastructure projects. You can also still reference MSTest in your test infrastructure projects, but it is a good idea to make all test base classes `abstract`.
