### ISSUE TITLE
Provide additional information for assert failures

### ISSUE THREAD

**Issue by codito** [Microsoft/testfx#334]
## Description
Default `Assert` methods should provide information in case of failures. They should at least answer the next question for a developer once a failure occurs. I've seen this scenarios with `CollectionAsserts`, request to review other APIs as well.

## Steps to reproduce
1. Create a hello world test project
2. Add two `List<int>` variables. `var actual = { 1, 2, 3 }` and `expected = { 1, 3, 2 }`
3. Add an assert. `CollectionAssert.AreEqual(expected, actual)`
4. Run tests

## Expected behavior
A developer would immediately ask what were the elements if the collection doesn't match. Note the `**additional**` information below.

```
Failed   C.Tests.N.D
Error Message:
 CollectionAssert.AreEqual failed. (Element at index 1 do not match.)
 **Expected = { 2, 1, 3 }, Actual = { 1, 2, 3 }**
Stack Trace:
   at C.Tests.N.D()
```

## Actual behavior
```
Failed   C.Tests.N.D
Error Message:
 CollectionAssert.AreEqual failed. (Element at index 1 do not match.)
Stack Trace:
   at C.Tests.N.D()
```

## Environment
MSTest 1.2.0, VSTest 15.3.0, dotnet-sdk 2.0 (linux)

**Comment by GoFightNguyen** [comment]
This is a great issue. If this functionality gets added, then great. But I think we should also consider using [Fluent Assertions](https://github.com/fluentassertions/fluentassertions).

I used your example and Fluent Assertions for the asserts.

`actual.Should().BeEquivalentTo(expected);`
This passes, because it does not care about ordering.

If I do `actual.Should().BeEquivalentTo(expected, o => o.WithStrictOrdering());`, then the test output is
> Message: Expected item[1] to be a collection with 3 item(s)Expected item[1] to be 3, but found 2.
Expected item[2] to be a collection with 3 item(s)Expected item[2] to be 2, but found 3.

Admittedly, that message has unnecessary and redundant information
>Expected item[1] to be a collection with 3 item(s)
>Expected item[2] to be a collection with 3 item(s)

I'll have to open an issue, because the previous version of Fluent Assertions did not include that cruft.

**Comment by ckamunya11** [comment]
cruft

**Comment by Evangelink** [comment]
Closing as resolved by [RFC 012 — Structured Assertion Messages](https://github.com/microsoft/testfx/blob/main/docs/RFCs/012-Structured-Assertion-Messages.md) (umbrella tracking PR #7750, infrastructure in #8170, and the family of per-API migration PRs that followed).

Every `Assert.*` failure message now follows a consistent structured layout: an `Assertion failed. <summary>` headline, optional user message, an evidence block (`expected: …`, `actual: …`, plus assertion-specific details like `delta:`, `ignore case:`, `culture:`, `comparison:`, `comparer:`), and a reconstructed call-site expression at the bottom. That covers the original ask — "developers should immediately see what was expected, what was actual, and what failed" — across every `Assert.*` method.

For `CollectionAssert` specifically, the modernised replacements live on `Assert` itself: `Assert.AreSequenceEqual` / `AreNotSequenceEqual` (#8334), `Assert.AreEquivalent` / `AreNotEquivalent` (#8266), `Assert.ContainsAll` / `DoesNotContainAll` (#8234), `Assert.AreAllNotNull` / `AreAllDistinct` / `AreAllOfType` (#8237), `Assert.HasCount` / `IsEmpty` / `IsNotEmpty`, etc. All of those use the RFC 012 format.

If you hit a *specific* case where a message is still unclear, please open a focused issue with a repro — thanks!
