### ISSUE TITLE
dotnet test fails when trying to execute Assembly.DefinedTypes or Assembly.GetTypes

### ISSUE THREAD

**Issue by derhally** [Microsoft/testfx#341]
## Description
The following exception occurs when executing Assembly.GetTypes() or Assembly.DefinedTypes inside .net core sdk container

```
Failed   Test
Error Message:
 System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
  ----> System.TypeLoadException : Could not load type 'Microsoft.VisualStudio.TestPlatform.ObjectModel.Navigation.DiaSourceClass' from assembly 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
Stack Trace:
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at TestIssue.TestClass.Test() in /temp/TestIssue/TestIssue/Class1.cs:line 16
--TypeLoadException
```

## Steps to reproduce

1. Copy the project to a container image of microsoft/dotnet:sdk 
[TestIssue.zip](https://github.com/Microsoft/testfx/files/1596121/TestIssue.zip)

2. Run dotnet build -c Release

3. Run dotnet test -c Release

## Expected behavior
All tests pass

## Actual behavior

Exception is thrown

```
System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
  ----> System.TypeLoadException : Could not load type 'Microsoft.VisualStudio.TestPlatform.ObjectModel.Navigation.DiaSourceClass' from assembly 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

## Environment

Container using sdk image

**Comment by derhally** [comment]
@smadala any thoughts or updates on this?

**Comment by smadala** [comment]
@derhally Sorry for leave you hanging, I didn't get change to investigate this, Will get back to you soon. 
Adding `Microsoft.VisualStudio.TestPlatform.ObjectModel:15.5.0` package reference explicitly helps?

**Comment by jmeline** [comment]
I'm running into the same issue. I tried the TestIssue.zip and was met with the same error. I'm interested in any updates to this issue.

```
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

**Comment by derhally** [comment]
@smadala did you mean to say "Microsoft.TestPlatform.ObjectModel" ?  

I tried that and still get the same error

```
 System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
  ----> System.TypeLoadException : Could not load type 'Microsoft.VisualStudio.TestPlatform.ObjectModel.Navigation.DiaSourceClass' from assembly 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
Stack Trace:
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()

```

**Comment by smadala** [comment]
This issue was moved to Microsoft/vstest#1417
