### ISSUE TITLE
[Testing Platform] System.InvalidOperationException: Console is already in batching mode.

### ISSUE THREAD

**Issue by thomhurst** [microsoft/testfx#3714]
Package Version: 1.4.0-preview24422.11

Looking at the code, there isn't a lock around `TestProgressStateAwareTerminal` lines 138-140.

So I'm guessing that the `StartUpdate` there is called, and then the `ThreadProc` method repeats its loop, nothing has the `_lock` lock and that tries to call `StartUpdate` too and thus an exception is thrown.

Stacktrace:

```
Error: Unhandled exception. System.InvalidOperationException: Console is already in batching mode.
   at Microsoft.Testing.Platform.OutputDevice.Terminal.NonAnsiTerminal.StartUpdate() in /_/src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/NonAnsiTerminal.cs:line 125
   at Microsoft.Testing.Platform.OutputDevice.Terminal.TestProgressStateAwareTerminal.ThreadProc() in /_/src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TestProgressStateAwareTerminal.cs:line 45
   at System.Threading.Thread.StartCallback()
```

**Comment by nohwnd** [comment]
Thanks for the analysis, I think this is happening when tests are completing at the same time and trying to write their results. The code is in the path where we know that progress is disabled, so it should not be caused by the progress update loop.
