### ISSUE TITLE
TrxExceptionProperty and InnerException

### ISSUE THREAD

**Issue by thomhurst** [microsoft/testfx#3969]
Only just considered this.

You completed #3920 today - But the trx property will probably need adjusting too:

```
public sealed record TrxExceptionProperty(string? Message, string? StackTrace) : IProperty;
```

This currently takes a message and a stacktrace, which will only ever be the top level message + stacktrace.

Again, if we're using wrapped/aggregate exceptions, then we lose visibility of those inner throws.

**Comment by Evangelink** [comment]
I'll check what VSTest is doing in this case and report back.

**Comment by Evangelink** [comment]
Given the following test class:

```cs
namespace TestProject2
{
    [TestClass]
    public class Test1
    {
        [TestMethod]
        public void TestMethod1()
        {
            try
            {
                throw new InvalidOperationException("error");
            }
            catch (Exception e)
            {
                throw new Exception("catch error", e);
            }
        }
    }
}
```

The trx produced with VSTest is:

```xml
<?xml version="1.0" encoding="utf-8"?>
<TestRun id="3b0cc85f-899f-4859-9059-d581610bebf7" name="amauryleve@LAPTOP-AMO-MS 2024-10-24 15:28:32" runUser="EUROPE\amauryleve" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2024-10-24T15:28:32.0480832+02:00" queuing="2024-10-24T15:28:32.0480832+02:00" start="2024-10-24T15:28:31.2334339+02:00" finish="2024-10-24T15:28:32.0780889+02:00" />
  <TestSettings name="default" id="374b8037-9daa-4fbb-b14f-ca57c9804f86">
    <Deployment runDeploymentRoot="amauryleve_LAPTOP-AMO-MS_2024-10-24_15_28_32" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="fccc224c-479c-4f3f-b44c-3ac52d1fe9b7" testId="fec66d05-e11c-7621-7344-3566ab9ecb34" testName="TestMethod1" computerName="LAPTOP-AMO-MS" duration="00:00:00.0138633" startTime="2024-10-24T15:28:31.8481136+02:00" endTime="2024-10-24T15:28:31.8809312+02:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="fccc224c-479c-4f3f-b44c-3ac52d1fe9b7">
      <Output>
        <ErrorInfo>
          <Message>Test method TestProject2.Test1.TestMethod1 threw exception: &#xD;
System.Exception: catch error ---&gt; System.InvalidOperationException: error</Message>
          <StackTrace>    at TestProject2.Test1.TestMethod1() in C:\src\temp\TestProject8\TestProject2\Test1.cs:line 11&#xD;
--- End of inner exception stack trace ---&#xD;
    at TestProject2.Test1.TestMethod1() in C:\src\temp\TestProject8\TestProject2\Test1.cs:line 15&#xD;
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)&#xD;
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)&#xD;
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
  <TestDefinitions>
    <UnitTest name="TestMethod1" storage="c:\src\temp\testproject8\testproject2\bin\debug\net8.0\testproject2.dll" id="fec66d05-e11c-7621-7344-3566ab9ecb34">
      <Execution id="fccc224c-479c-4f3f-b44c-3ac52d1fe9b7" />
      <TestMethod codeBase="C:\src\temp\TestProject8\TestProject2\bin\Debug\net8.0\TestProject2.dll" adapterTypeName="executor://mstestadapter/v2" className="TestProject2.Test1" name="TestMethod1" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="fec66d05-e11c-7621-7344-3566ab9ecb34" executionId="fccc224c-479c-4f3f-b44c-3ac52d1fe9b7" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" passed="0" failed="1" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>Test Parallelization enabled for C:\src\temp\TestProject8\TestProject2\bin\Debug\net8.0\TestProject2.dll (Workers: 16, Scope: MethodLevel)&#xD;
</StdOut>
    </Output>
  </ResultSummary>
</TestRun>
```

TRX with MTP:

```xml
<?xml version="1.0" encoding="utf-8"?>
<TestRun id="af785038-34a7-486d-834f-20805a105066" name="amauryleve@LAPTOP-AMO-MS 2024-10-24 13:29:55.511" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2024-10-24T13:29:55.3631149Z" queuing="2024-10-24T13:29:55.3631149Z" start="2024-10-24T13:29:55.3631149Z" finish="2024-10-24T13:29:55.5131058Z" />
  <TestSettings name="default" id="64847ba9-8398-4df0-a0fe-07a39ca2e0eb">
    <Deployment runDeploymentRoot="amauryleve_LAPTOP-AMO-MS_2024-10-24_13_29_55.511" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="517d4980-f04c-461e-95e8-4a0cb806cfd7" testId="ceb75fd6-0762-cef0-c934-fac4c8424089" testName="TestMethod1" computerName="LAPTOP-AMO-MS" duration="00:00:00.0170915" startTime="2024-10-24T13:29:55.4652273+00:00" endTime="2024-10-24T13:29:55.4996011+00:00" testType="13CDC9D9-DDB5-4fa4-A97D-D965CCFC6D4B" outcome="Failed" testListId="8C84FA94-04C1-424b-9868-57A2D4851A1D" relativeResultsDirectory="517d4980-f04c-461e-95e8-4a0cb806cfd7">
      <Output>
        <ErrorInfo>
          <Message>Test method TestProject2.Test1.TestMethod1 threw exception: 
System.Exception: catch error ---&gt; System.InvalidOperationException: error</Message>
          <StackTrace>    at TestProject2.Test1.TestMethod1() in C:\src\temp\TestProject8\TestProject2\Test1.cs:line 11
--- End of inner exception stack trace ---
    at TestProject2.Test1.TestMethod1() in C:\src\temp\TestProject8\TestProject2\Test1.cs:line 15
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
  <TestDefinitions>
    <UnitTest name="TestMethod1" storage="c:\src\temp\testproject8\testproject2\bin\debug\net8.0\testproject2.dll" id="ceb75fd6-0762-cef0-c934-fac4c8424089">
      <Execution id="517d4980-f04c-461e-95e8-4a0cb806cfd7" />
      <TestMethod codeBase="C:\src\temp\TestProject8\TestProject2\bin\Debug\net8.0\TestProject2.dll" adapterTypeName="executor://MSTest.Sdk/3.6.1" className="TestProject2.Test1" name="TestMethod1" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="ceb75fd6-0762-cef0-c934-fac4c8424089" executionId="517d4980-f04c-461e-95e8-4a0cb806cfd7" testListId="8C84FA94-04C1-424b-9868-57A2D4851A1D" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8C84FA94-04C1-424b-9868-57A2D4851A1D" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" passed="0" failed="1" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
</TestRun>
```

So I would say we are good.
