### ISSUE TITLE
Cancelled tests not reported as failures

### ISSUE THREAD

**Issue by thomhurst** [microsoft/testfx#4196]
See this run: https://github.com/thomhurst/ModularPipelines/actions/runs/12072550368/job/33666771665?pr=787#step:9:3473

Cancelled tests are marked as failures.

I'd argue they shouldn't be counted as failures as that's misleading. They haven't failed per se, they were just terminated.

If the overall test run was cancelled it should fail overall, but not each cancelled test imo.

What do you think?

**Comment by Evangelink** [comment]
Is this functionally expected to have a test being cancelled? For me, it is an error even if that's the result of a user requesting cancellation.

We cannot say the test is ok as it didn't reach the end of its action.

**Comment by thomhurst** [comment]
> We cannot say the test is ok as it didn't reach the end of its action.

This is similar to #3699 I think.
It's more inconclusive than failed. If the test framework marks then as cancelled, I'd say it's inconclusive. If it didn't cancel, it might have passed, or it might have failed, we don't know.

The overall run should still fail, but it can create noise in the logs or test explorer when trying to find actual failures.

**Comment by thomhurst** [comment]
My use case is I have exposed a `--fail-fast` flag in TUnit. So if you've got a large test suite that takes ages to run, there's the option to fail quickly on the first failure. The first failure will cancel the test session's cancellation token, and so all pending tests would then be marked as cancelled. Sifting through the output/test explorer to find that failure is harder if all the cancellations look like failures too.

**Comment by Evangelink** [comment]
I understand the TE situation, let's put it on the side for a second to focus on CLI experience, what would be your expectations there?

**Comment by thomhurst** [comment]
Personally I wouldn't count them under the failure counter, and I find the stacktrace clutter that makes real failures harder to find 

E.g.
```
failed (canceled) Has_Not_Errored (0ms)
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at TUnit.Engine.Framework.TUnitTestFramework.ExecuteRequestAsync(ExecuteRequestContext context)
failed Unhandled exception - TaskCanceledException: A task was canceled. (0ms)
  System.Threading.Tasks.TaskCanceledException: A task was canceled.
    at TUnit.Engine.Framework.TUnitTestFramework.ExecuteRequestAsync(ExecuteRequestContext context)
```

**Comment by nohwnd** [comment]
Sounds reasonable to me to not report it as error as long as we guarantee that the whole run will finish with error code.

**Comment by thomhurst** [comment]
Tbh no I can just map them to failures, I don't have a strong opinion.

I originally raised this issue because if they just get reported as a failure, What's the point of the different status?

Same can probably be said for timeout, pretty much just ends up as a failure too.

**Comment by thomhurst** [comment]
I just used cancelled because it was there as an option. I thought best to use the most specific status I can map too. But I would've just settled for failure had it not been there.

In regards to throwing and bubbling back to MTP, that doesn't really work. You get unclear errors like Test framework reported a start event but not an end event (or something like that, can't remember off the top of my head.)

**Comment by Youssef1313** [comment]
> In regards to throwing and bubbling back to MTP, that doesn't really work. You get unclear errors like Test framework reported a start event but not an end event (or something like that, can't remember off the top of my head.)

Can you have more clear repro of what goes wrong when you throw cancellation and let the flow back to MTP? I would prefer to address that instead, and then obsolete the cancelled state.

**Comment by Youssef1313** [comment]
Exactly. Cancellation should happen via `cancellationToken.ThrowIfCancellationRequested()`, and only using the `cancellationToken` that MTP passes to the framework.

**Comment by thomhurst** [comment]
I see. While on the subject, I still think you should provide framework authors a way to cancel that MTP cancellation token: https://github.com/microsoft/testfx/issues/5558
