### ISSUE TITLE
MSTestAdapter .dll Error - I wasn't able to run the test.

### ISSUE THREAD

**Issue by lsusada** [Microsoft/testfx#558]
Hello everyone,

I am new here. But hoping you help me with regards to my issues encountered in VS 2017.

So, I have this project get from the Source-Control > I added a mapping to C:\VS > Get Latest version of the project.
And suddenly this message appear:
![image](https://user-images.githubusercontent.com/46878216/52028307-7ce91080-2549-11e9-93dc-a5740d92628d.png)

Weather I Add the Item or not, I still can't Debug or Run the Test. This is the error I got:
```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Helpers.DotnetHostHelper.TryGetExecutablePath(String executableBaseName, String& executablePath)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Helpers.DotnetHostHelper.GetDotnetPath()
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)

```

**Comment by karanjitsingh** [comment]
@lsusada, I'm not able to understand your problem here, could you please elaborate on this:

> So, I have this project get from the Source-Control > I added a mapping to C:\VS > Get Latest version of the project.

**Comment by nigurr** [comment]
@lsusada Please refer TFVC source documentations on how to ignore these warnings.
https://stackoverflow.com/questions/922798/how-to-ignore-files-directories-in-tfs-for-avoiding-them-to-go-to-central-source
https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/?view=azure-devops
