### ISSUE TITLE
System.Reflection.ReflectionTypeLoadException (only on mac / linux)

### ISSUE THREAD

**Issue by maurei** [Microsoft/testfx#583]
## Description

This error is caused in one of my xUnit tests, but I believe has nothing to do with xUnit. The problem does not occur on windows, only linux and mac.

```
Error Message:
 System.AggregateException : One or more errors occurred. (Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.) (The following constructor parameters did not have matching fixture data: TestFixture fixture)
---- System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
---- The following constructor parameters did not have matching fixture data: TestFixture fixture
Stack Trace:

----- Inner Stack Trace #1 (System.Reflection.ReflectionTypeLoadException) -----
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at AutoMapper.ServiceCollectionExtensions.AddAutoMapperClasses(IServiceCollection services, Action`1 additionalInitAction, IEnumerable`1 assembliesToScan)
   at ResourceEntitySeparationExample.Startup.ConfigureServices(IServiceCollection services) in /Users/Moeys/Code/rs/rs-api/JsonApiDotNetCore/src/Examples/ResourceEntitySeparationExample/Startup.cs:line 59
   at ResourceEntitySeparationExampleTests.TestStartup.ConfigureServices(IServiceCollection services) in /Users/Moeys/Code/rs/rs-api/JsonApiDotNetCore/test/ResourceEntitySeparationExampleTests/TestStartup.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.AspNetCore.TestHost.TestServer..ctor(IWebHostBuilder builder, IFeatureCollection featureCollection)
   at ResourceEntitySeparationExampleTests.TestFixture..ctor() in /Users/Moeys/Code/rs/rs-api/JsonApiDotNetCore/test/ResourceEntitySeparationExampleTests/TestFixture.cs:line 30
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```

## Steps to reproduce
To reproduce the errors, please clone [this project](https://github.com/json-api-dotnet/JsonApiDotNetCore/) and run the [ResourceEntitySeparationExampleTests](
https://github.com/json-api-dotnet/JsonApiDotNetCore/tree/master/test/ResourceEntitySeparationExampleTests). Don't forget to remove the [docfx package reference](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/071ce9fc11c857d40419625519cc8cd290dc1428/src/JsonApiDotNetCore/JsonApiDotNetCore.csproj#L45), else the project won't build :)

## Expected behavior
no error

## Actual behavior
error

## Environment
.NET Core SDK 
Version:   2.2.102 (but same error on all previous SDKs afaik
 Commit:    96ff75a873

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.102/

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

**Comment by cltshivash** [comment]
This repo is for MSTest Framework. From the description, you will need to report this in the xUnit repo.
