### ISSUE TITLE
Repo has unit test runtime dependency on deprecated .NET Core version

### ISSUE THREAD

**Issue by jimmylewis** [microsoft/testfx#642]
## Description
When cloning and running tests in this repo, there is a runtime dependency on having .NET Core 1.1 installed (specifically, for `ValidateTimeoutTestsNetCore`).  If .NET Core 1.1 is not installed, this test will fail unintuitively - it will say that 0 of the test cases timed out (expected 2).  In reality, they never ran (or failed to start).

.NET Core 1.1 is beyond its support lifecycle, so it will be increasingly common for developers to *not* have it present.

## Steps to reproduce
> What steps can reproduce the defect?

On a clean machine, install VS2019 (it no longer offers any way to acquire .NET Core 1.1), clone this repo, build, and run tests.

## Expected behavior
Tests should all pass, _or_ should fail with an accurate message.

## Actual behavior

>Failed   ValidateTimeoutTestsNetCore
Error Message:
 Test method MSTestAdapter.Smoke.E2ETests.TimeoutTests.ValidateTimeoutTestsNetCore threw exception: 
Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Assert.AreEqual failed. **Expected:<2>. Actual:<0>.** 
Stack Trace:
   at Microsoft.MSTestV2.CLIAutomation.CLITestBase.ValidateFailedTestsCount(Int32 expectedFailedTestsCount) in D:\a\1\s\test\E2ETests\Automation.CLI\CLITestBase.cs:line 152
   at MSTestAdapter.Smoke.E2ETests.TimeoutTests.Validate(String testAssembly, String fileToValidate) in D:\a\1\s\test\E2ETests\Smoke.E2E.Tests\TimeoutTests.cs:line 38
   at MSTestAdapter.Smoke.E2ETests.TimeoutTests.ValidateTimeoutTestsNetCore() in D:\a\1\s\test\E2ETests\Smoke.E2E.Tests\TimeoutTests.cs:line 29

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console, Package version of MSTest
> framework and adapter

**Comment by mayankbansal018** [comment]
We understand that this is an issue for machines with VS 2019, & no .Net Core 1.1 available. Unfortunately we are not able to pick this up at this time. I've marked it as up for grabs, & will be happy to take up contributions from community.

**Comment by eriawan** [comment]
@mayankbansal018 

I would like to pick this up to prepare for VS 2019.

I also will update the Windows 10 SDK support to at least supporting 1903, because current master branch code has support for Windows 10 14393, and this build of 14393 is also not supported anymore.

**Comment by Haplois** [comment]
Yes :)
