### ISSUE TITLE
Failed to initialize code coverage datacollector

### ISSUE THREAD

**Issue by sakno** [microsoft/testfx#729]
## Description
I just updated `Microsoft.NET.Test.Sdk 16.6.1` and got the following exception:
```
Data collector 'Code Coverage' message: Failed to initialize code coverage datacollector with error: System.TypeLoadException: Could not load type 'Microsoft.VisualStudio.TestPlatform.Utilities.CodeCoverageRunSettingsProcessor' from assembly 'Microsoft.TestPlatform.Utilities, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollectorImpl.Initialize(XmlElement configurationElement, IDataCollectionSink dataSink, IDataCollectionLogger logger)
   at Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector.OnInitialize(XmlElement configurationElement).
Data collector 'Code Coverage' message: Data collector 'Code Coverage' threw an exception during type loading, construction, or initialization: System.TypeLoadException: Could not load type 'Microsoft.VisualStudio.TestPlatform.Utilities.CodeCoverageRunSettingsProcessor' from assembly 'Microsoft.TestPlatform.Utilities, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollectorImpl.Initialize(XmlElement configurationElement, IDataCollectionSink dataSink, IDataCollectionLogger logger)
   at Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector.OnInitialize(XmlElement configurationElement)
   at Microsoft.VisualStudio.TraceCollector.BaseDataCollector.Initialize(XmlElement configurationElement, IDataCollectionEvents events, IDataCollectionSink dataSink, IDataCollectionLogger logger, IDataCollectionAgentContext agentContext)
   at Microsoft.VisualStudio.TraceCollector.BaseDataCollector.Initialize(XmlElement configurationElement, DataCollectionEvents events, DataCollectionSink dataSink, DataCollectionLogger logger, DataCollectionEnvironmentContext environmentContext)
   at Microsoft.VisualStudio.TestPlatform.Common.DataCollector.DataCollectorInformation.InitializeDataCollector()
   at Microsoft.VisualStudio.TestPlatform.Common.DataCollector.DataCollectionManager.LoadAndInitialize(DataCollectorSettings dataCollectorSettings, String settingsXml)..
```

Collection of code coverage metrics is performed on Windows machine in Azure. Here is the [link to the log](https://dev.azure.com/rvsakno/dotNext/_build/results?buildId=794&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=ea74d3ec-af51-57bf-65e6-f50dd234a1e5&l=41).

On Linux machine (Ubuntu 18.04), everything is fine.

## Steps to reproduce
Update from `Microsoft.NET.Test.Sdk 16.6.1` to `Microsoft.NET.Test.Sdk 16.7.0`

## Expected behavior
Code coverage collection should be completed successfully

## Actual behavior
`TypeLoadException` occurred.

## Environment
Azure Pipelines
`windows-2019` hosted agent

**Comment by sakno** [comment]
`windows-2019` doesn't have installed .NET Core 3.1.401 according with [this page](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md). I'm closing this issue.
