### ISSUE TITLE
v2.2.4 DataRow - breaking change in conversion of double values

### ISSUE THREAD

**Issue by rikrak** [microsoft/testfx#842]
## Description
MSTest interprets constant double values as decimals, which is a change from previous behaviour

## Steps to reproduce
Using the following Code:

    using Microsoft.VisualStudio.TestTools.UnitTesting;
    namespace MStest.DataRowExample
    {
        [TestClass]
        public class Class1
        {
            [DataRow(1,2,3)]
            [TestMethod]
            public void DataRowTest_1(double x, double y, double expected)
            {
                // arrange
                
                // act
                var actual = x + y;
    
                // assert
                Assert.AreEqual(expected, actual);
            }
    
            [DataRow(1.1, 2.2, 3.3)]
            [TestMethod]
            public void DataRowTest_2(double x, double y, double expected)
            {
                // arrange
                
                // act
                var actual = x + y;
    
                // assert
                Assert.AreEqual(expected, actual);
            }
    
            [DataRow(1.11111111, 2.22222222, 3.33333333)]
            [TestMethod]
            public void DataRowTest_3(double x, double y, double expected)
            {
                // arrange
                
                // act
                var actual = x + y;
    
                // assert
                Assert.AreEqual(expected, actual);
            }
    
        }
     }

## Expected behavior
All tests should pass (as they do with the previous version of MSTest)

## Actual behavior
Tests 2 & 3 fail with:

    threw exception: 
    System.ArgumentException: Object of type 'System.Decimal' cannot be converted to type 'System.Double'.
        at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
       at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
       at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
       at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
       at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)

## Environment

- MSTest 2.2.4
- .NET Framework 4.8
- Windows 10
- VS 2019 (16.10.0)

**Comment by rikrak** [comment]
Could this be related to #837 ?

**Comment by Haplois** [comment]
@rikrak, thank you for reporting this, it's a known issue - we're working on it. It's tracked [here][1].

[1]: https://github.com/microsoft/testfx/issues/837

**Comment by Haplois** [comment]
Ref: https://github.com/microsoft/vstest/issues/2925
