### ISSUE TITLE
MSTest.TestAdapter v2.2.4 fails on execution of tests in net5.0-windows10.0.19041 project

### ISSUE THREAD

**Issue by xantiva** [microsoft/testfx#852]
## Description
After updating MSTest.TestAdapter from 2.2.3 to 2.2.4 a test project with the target framework net5.0-windows10.0.19041, the test execution throws an exception and only some tests have been executed.

```
========== Starting test run ==========
[MSTest][Discovery][C:\source\xxxxx\Controlboard.Tests\bin\Debug\net5.0-windows10.0.19041\yyyyyyy.Controlboard.Tests.dll] Failed to discover tests from assembly C:\source\xxxxx\Controlboard.Tests\bin\Debug\net5.0-windows10.0.19041\yyyyyyy.Controlboard.Tests.dll. Reason:File does not exist: C:\source\xxxxx\Controlboard.Tests\bin\Debug\net5.0-windows10.0.19041\yyyyyyy.Controlboard.Tests.dll
Kein Test entspricht dem angegebenen Testfallfilter "FullyQualifiedName=zzzzzzzz.Controlboard.Bootstrapping.Tests.ControlboardServiceRegistrationModuleTests.CheckNumberOfRegisteredTypes|FullyQualifiedName=zzzzzzzz.Controlboard.Bootstrapping.Tests.ControlboardServiceRegistrationModuleTests.Resolve|FullyQu..." in "C:\source\xxxxx\Controlboard.Tests\bin\Debug\net5.0-windows10.0.19041\yyyyyyy.Controlboard.Tests.dll".
Ausnahme beim Aufrufen von Executor "executor://mstestadapter/v2": Type 'System.RuntimeType' cannot be serialized. Consider marking it with the DataContractAttribute attribute, and marking all of its members you want serialized with the DataMemberAttribute attribute. Alternatively, you can ensure that the type is public and has a parameterless constructor - all public members of the type will then be serialized, and no attributes will be required.
Stapelüberwachung:
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.ThrowInvalidDataContractException(String message, Type type)
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(Type type)
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(Int32 id, RuntimeTypeHandle typeHandle, Type type)
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetDataContractSkipValidation(Int32 id, RuntimeTypeHandle typeHandle, Type type)
   at System.Runtime.Serialization.DataContract.GetDataContract(RuntimeTypeHandle typeHandle, Type type, SerializationMode mode)
   at System.Runtime.Serialization.DataContractSerializer.GetDataContract(DataContract declaredTypeContract, Type declaredType, Type objectType)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.InternalWriteObjectContent(XmlWriterDelegator writer, Object graph)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.InternalWriteObject(XmlWriterDelegator writer, Object graph)
   at System.Runtime.Serialization.XmlObjectSerializer.InternalWriteObject(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.WriteObject(XmlDictionaryWriter writer, Object graph)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.WriteObject(Stream stream, Object graph)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Helpers.DataSerializationHelper.Serialize(Object[] data)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.ObjectModel.UnitTestElement.ToTestCase()
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.UnitTestDiscoverer.SendTestCases(String source, IEnumerable`1 testElements, ITestCaseDiscoverySink discoverySink, IDiscoveryContext discoveryContext, IMessageLogger logger)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.UnitTestDiscoverer.DiscoverTestsInSource(String source, IMessageLogger logger, ITestCaseDiscoverySink discoverySink, IDiscoveryContext discoveryContext)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestExecutionManager.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle, TestRunCancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.MSTestExecutor.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.RunTestsWithSources.InvokeExecutor(LazyExtension`2 executor, Tuple`2 executorUriExtensionTuple, RunContext runContext, IFrameworkHandle frameworkHandle)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestInternalWithExecutors(IEnumerable`1 executorUriExtensionMap, Int64 totalTests)

Ausnahme beim Aufrufen von Executor "executor://mstestadapter/v2": Type 'System.RuntimeType' cannot be serialized. Consider marking it with the DataContractAttribute attribute, and marking all of its members you want serialized with the DataMemberAttribute attribute. Alternatively, you can ensure that the type is public and has a parameterless constructor - all public members of the type will then be serialized, and no attributes will be required.
Stapelüberwachung:
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.ThrowInvalidDataContractException(String message, Type type)
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(Type type)
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(Int32 id, RuntimeTypeHandle typeHandle, Type type)
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetDataContractSkipValidation(Int32 id, RuntimeTypeHandle typeHandle, Type type)
   at System.Runtime.Serialization.DataContract.GetDataContract(RuntimeTypeHandle typeHandle, Type type, SerializationMode mode)
   at System.Runtime.Serialization.DataContractSerializer.GetDataContract(DataContract declaredTypeContract, Type declaredType, Type objectType)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.InternalWriteObjectContent(XmlWriterDelegator writer, Object graph)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.InternalWriteObject(XmlWriterDelegator writer, Object graph)
   at System.Runtime.Serialization.XmlObjectSerializer.InternalWriteObject(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.WriteObject(XmlDictionaryWriter writer, Object graph)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.WriteObject(Stream stream, Object graph)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Helpers.DataSerializationHelper.Serialize(Object[] data)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.ObjectModel.UnitTestElement.ToTestCase()
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.UnitTestDiscoverer.SendTestCases(String source, IEnumerable`1 testElements, ITestCaseDiscoverySink discoverySink, IDiscoveryContext discoveryContext, IMessageLogger logger)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.UnitTestDiscoverer.DiscoverTestsInSource(String source, IMessageLogger logger, ITestCaseDiscoverySink discoverySink, IDiscoveryContext discoveryContext)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestExecutionManager.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle, TestRunCancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.MSTestExecutor.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.RunTestsWithSources.InvokeExecutor(LazyExtension`2 executor, Tuple`2 executorUriExtensionTuple, RunContext runContext, IFrameworkHandle frameworkHandle)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestInternalWithExecutors(IEnumerable`1 executorUriExtensionMap, Int64 totalTests)

========== Test run finished: 376 Tests (375 Passed, 0 Failed, 1 Skipped) run in 3,1 sec ==========
```

I've got also an error with this target framework, if I update the TestFramework: https://github.com/microsoft/testfx/issues/851

I need this target framework for Rx 5: https://github.com/dotnet/reactive/issues/1497

## Steps to reproduce
All tests could be executed with the MSTest.Testadapter 2.2.3. After upgrading the nuget package to 2.2.4, deleting bin and obj folders, rebuilding the solution the error occures, if I want to execute the unit tests again.

## Environment
Visual Studio 16.10.0
Microsoft.NET.Test.Sdk Version="16.10.0"
MSTest.TestAdapter Version="2.2.4"
MSTest.TestFramework Version="2.2.3"

**Comment by Haplois** [comment]
Thank you for reporting this, it's a known issue - we're working on it. It's tracked [here][1], there is a [preview version][2] addressing this issue is out, you could switch to it meanwhile we're working on releasing the fix. 

[1]: https://github.com/microsoft/testfx/issues/844
[2]: https://github.com/microsoft/testfx/issues/844#issuecomment-851429634

**Comment by xantiva** [comment]
Hello haplois,

I'm sorry, but the 2.2.5-preview-20210605-01 version of the MSTest.TestAdapter doesn't fix all of the errors. Or works it only together with the preview of the TestFramework? (This preview doesn't fix my other compiler errors yet, so I can't use it.)

```
    <PackageReference Include="MSTest.TestAdapter" Version="2.2.5-preview-20210605-01" />
    <PackageReference Include="MSTest.TestFramework" Version="2.2.3" />
```

I clean the solution, delete all bin and obj folders and close and reopen Visual Studio. After that I rebuild the solution and execute the tests.

  Tests in group: 898
   Total Duration: 16,5 sec

Outcomes
   **80 Not Run**
   817 Passed
   1 Skipped


```
========== Starting test run ==========
[MSTest][Discovery][C:\source\xxx\Controlboard.Tests\bin\Debug\net5.0-windows10.0.19041\yyy.Controlboard.Tests.dll] Failed to discover tests from assembly C:\source\xxx\Controlboard.Tests\bin\Debug\net5.0-windows10.0.19041\yyy.Controlboard.Tests.dll. Reason:File does not exist: C:\source\xxx\Controlboard.Tests\bin\Debug\net5.0-windows10.0.19041\yyy.Controlboard.Tests.dll
Kein Test entspricht dem angegebenen Testfallfilter "FullyQualifiedName=zzz.Controlboard.Bootstrapping.Tests.ControlboardServiceRegistrationModuleTests.CheckNumberOfRegisteredTypes|FullyQualifiedName=zzz.Controlboard.Bootstrapping.Tests.ControlboardServiceRegistrationModuleTests.Resolve|FullyQu..." in "C:\source\xxx\Controlboard.Tests\bin\Debug\net5.0-windows10.0.19041\yyy.Controlboard.Tests.dll".
========== Test run finished: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in 103 ms ==========
========== Starting test run ==========
[MSTest][Discovery][C:\source\xxx\Controlboard.Tests\bin\Debug\net5.0-windows10.0.19041\yyy.Controlboard.Tests.dll] Failed to discover tests from assembly C:\source\xxx\Controlboard.Tests\bin\Debug\net5.0-windows10.0.19041\yyy.Controlboard.Tests.dll. Reason:File does not exist: C:\source\xxx\Controlboard.Tests\bin\Debug\net5.0-windows10.0.19041\yyy.Controlboard.Tests.dll
Kein Test entspricht dem angegebenen Testfallfilter "FullyQualifiedName=zzz.Imager.Device.Bootstrapping.Tests.PrototypeBServiceRegistrationModuleTests.CheckNumberOfRegisteredTypes|FullyQualifiedName=zzz.Imager.Device.Bootstrapping.Tests.PrototypeBServiceRegistrationModuleTests.Resolve|FullyQual..." in "C:\source\xxx\Controlboard.Tests\bin\Debug\net5.0-windows10.0.19041\yyy.Controlboard.Tests.dll".
========== Test run finished: 820 Tests (819 Passed, 0 Failed, 1 Skipped) run in 6,1 sec ==========
```

**Comment by Sanan07** [comment]
Use `2.2.5-preview-20210605-01` for `MSTest.TestFramework` package as well. Keep both of them in sync.

**Comment by xantiva** [comment]
Hi @Sanan07 , thanks for your fast response.

Than I have to wait, because the `MsTest.TestFramework` causes another error: https://github.com/microsoft/testfx/issues/851
