### ISSUE TITLE
Invoking tests fails since update of MSTest.TestAdapter to 2.2.4

### ISSUE THREAD

**Issue by cmenzi** [microsoft/testfx#861]
## Description
Since the update from 2.2.3 to 2.2.4 test execution does not work anymore.

## Steps to reproduce
Execute tests on 2.2.3, update with 2.2.4, execute tests

## Expected behavior
```
dotnet test .\source\tests\Buhler.IoT.GenericDataModel.Extensions.Tests\Buhler.IoT.GenericDataModel.Extensions.Tests.csproj
  Determining projects to restore...
  Restored C:\data\iot\iot-library\gdm-extensions\source\tests\Buhler.IoT.GenericDataModel.Extensions.Tests\Buhler.IoT.GenericDataModel.Extensions.Tests.csproj (in 514 ms).
  1 of 2 projects are up-to-date for restore.
  Buhler.IoT.GenericDataModel.Extensions -> C:\data\iot\iot-library\gdm-extensions\source\src\Buhler.IoT.GenericDataModel.Extensions\bin\Debug\netstandard2.0\Buhler.IoT.GenericDataModel.Extensions.dll
  Buhler.IoT.GenericDataModel.Extensions.Tests -> C:\data\iot\iot-library\gdm-extensions\source\tests\Buhler.IoT.GenericDataModel.Extensions.Tests\bin\Debug\net5.0\Buhler.IoT.GenericDataModel.Extensions.Tests.dll
Test run for C:\data\iot\iot-library\gdm-extensions\source\tests\Buhler.IoT.GenericDataModel.Extensions.Tests\bin\Debug\net5.0\Buhler.IoT.GenericDataModel.Extensions.Tests.dll (.NETCoreApp,Version=v5.0)
Microsoft (R) Test Execution Command Line Tool Version 16.10.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:   792, Skipped:     0, Total:   792, Duration: 1 s - Buhler.IoT.GenericDataModel.Extensions.Tests.dll (net5.0)
```

## Actual behavior
```
dotnet test .\source\tests\Buhler.IoT.GenericDataModel.Extensions.Tests\Buhler.IoT.GenericDataModel.Extensions.Tests.csproj
  Determining projects to restore...
  All projects are up-to-date for restore.
  Buhler.IoT.GenericDataModel.Extensions -> C:\data\iot\iot-library\gdm-extensions\source\src\Buhler.IoT.GenericDataModel.Extensions\bin\Debug\netstandard2.0\Buhler.IoT.GenericDataModel.Extensions.dll
  Buhler.IoT.GenericDataModel.Extensions.Tests -> C:\data\iot\iot-library\gdm-extensions\source\tests\Buhler.IoT.GenericDataModel.Extensions.Tests\bin\Debug\net5.0\Buhler.IoT.GenericDataModel.Extensions.Tests.dll
Test run for C:\data\iot\iot-library\gdm-extensions\source\tests\Buhler.IoT.GenericDataModel.Extensions.Tests\bin\Debug\net5.0\Buhler.IoT.GenericDataModel.Extensions.Tests.dll (.NETCoreApp,Version=v5.0)
Microsoft (R) Test Execution Command Line Tool Version 16.10.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
An exception occurred while invoking executor 'executor://mstestadapter/v2': Type 'System.Runtime.Serialization.DateTimeOffsetAdapter' with data contract name 'DateTimeOffset:http://schemas.datacontract.org/2004/07/System' is not expected. Add any types not known statically to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to DataContractSerializer.
Stack trace:
   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeAndVerifyType(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, Boolean verifyKnownType, RuntimeTypeHandle declaredTypeHandle, Type declaredType)
   at System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.SerializeWithXsiTypeAtTopLevel(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle originalDeclaredTypeHandle, Type graphType)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.InternalWriteObjectContent(XmlWriterDelegator writer, Object graph)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.InternalWriteObject(XmlWriterDelegator writer, Object graph)
   at System.Runtime.Serialization.XmlObjectSerializer.InternalWriteObject(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.WriteObject(XmlDictionaryWriter writer, Object graph)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.WriteObject(Stream stream, Object graph)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Helpers.DataSerializationHelper.Serialize(Object[] data)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.ObjectModel.UnitTestElement.ToTestCase()
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.UnitTestDiscoverer.SendTestCases(String source, IEnumerable`1 testElements, ITestCaseDiscoverySink discoverySink, IDiscoveryContext discoveryContext, IMessageLogger logger)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.UnitTestDiscoverer.DiscoverTestsInSource(String source, IMessageLogger logger, ITestCaseDiscoverySink discoverySink, IDiscoveryContext discoveryContext)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestExecutionManager.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle, TestRunCancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.MSTestExecutor.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.RunTestsWithSources.InvokeExecutor(LazyExtension`2 executor, Tuple`2 executorUriExtensionTuple, RunContext runContext, IFrameworkHandle frameworkHandle)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestInternalWithExecutors(IEnumerable`1 executorUriExtensionMap, Int64 totalTests)
```

## Environment
- Windows 10 20H2
- VS2019 16.10
- dotnet-sdk-5.0.300
- MSTest.TestAdapter 2.2.4

**Comment by Sanan07** [comment]
It looks know issue, and recently our team provided new nuget for it. Please refer #844 in comments below you will find new 2.2.5-preview packages. Please test with them.

**Comment by Haplois** [comment]
Thank you for reporting this, it's a known issue - we're working on it. It's tracked [here][1], there is a [preview version][2] addressing this issue is out, you could switch to it meanwhile we're working on releasing the fix. 

[1]: https://github.com/microsoft/testfx/issues/844
[2]: https://github.com/microsoft/testfx/issues/844#issuecomment-854287294
