### ISSUE TITLE
MSTest 2.2.5 does not work with [DataTestMethod] [DynamicData] and a complex object that has private properties set through constructor

### ISSUE THREAD

**Issue by CoeckelberghPJ** [microsoft/testfx#917]
Related to https://github.com/microsoft/testfx/issues/844
We also had this issue when upgrading to 2.2.4 and even 2.2.5 did not fix our issue.
The test still fail when the complex object is created through a constructor or static method and sets private properties.

I've created an example: https://github.com/CoeckelberghPJ/TestFxBug

**Comment by TheFireCookie** [comment]
I have the issue too!

**Comment by schibu007** [comment]
Me too. This is my example. It's basically a truth table of an `OR` operation between `Value1` and `Value2`:
```cs
[TestClass]
public class UnitTest2
{
    [TestMethod]
    [DynamicData(nameof(GetTestCases), DynamicDataSourceType.Method, DynamicDataDisplayName = nameof(GetDescription))]
    public void TestMethod1(Context context, bool expected)
    {
        Console.WriteLine($"{context}; Expected: {expected};");
        var result = context.Value1 || context.Value2;

        Assert.AreEqual(expected, result);
    }

    private static IEnumerable<object[]> GetTestCases()
    {
        object[] TestCase(bool value1, bool value2, bool expected)
        {
            var context = new Context();
            context.SetValue1(value1);
            context.SetValue2(value2);
            return new object[] { context, expected };
        }

        yield return TestCase(false, false, false);
        yield return TestCase(false, true, true);
        yield return TestCase(true, false, true);
        yield return TestCase(true, true, true);
    }

    public static string GetDescription(MethodInfo _, object[] objects) => $"{{{objects[0]}}}; Expected: {objects[1]};";

    public class Context
    {
        //public Context(object o = null) { }
        public bool Value1 { get; private set; }
        public bool Value2 { get; private set; }

        public void SetValue1(bool value) => Value1 = value;
        public void SetValue2(bool value) => Value2 = value;

        public override string ToString() => $"Value1: '{Value1}', Value2: '{Value2}'";
    }
}
```
Outcome:
![image](https://user-images.githubusercontent.com/45459443/129312162-ba0e976a-24c6-48af-80c3-3422f523e77b.png)

Interesting about this is that the description and the actual data seem to be out of sync.
Another information that might be of interest:

- It works if line `//public Context(object o = null) { }` gets uncommented
- It works if the setters of the properties `Value1` and `Value2` are changed to public
- It fails with `vstest.console.exe` too:
```
D:\Projects\ConsoleApp1\TestProject\bin\Debug\net5.0>vstest.console.exe TestProject.dll
Microsoft (R) Test Execution Command Line Tool Version 16.10.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Passed {Value1: 'False', Value2: 'False'}; Expected: False; [3 ms]
  Failed {Value1: 'False', Value2: 'True'}; Expected: True; [20 ms]
  Error Message:
   Assert.AreEqual failed. Expected:<True>. Actual:<False>.
  Stack Trace:
     at TestProject.UnitTest2.TestMethod1(Context context, Boolean expected) in D:\Projects\ConsoleApp1\TestProject\UnitTest2.cs:line 19

  Standard Output Messages:
 Value1: 'False', Value2: 'False'; Expected: True;


  Failed {Value1: 'True', Value2: 'False'}; Expected: True; [< 1 ms]
  Error Message:
   Assert.AreEqual failed. Expected:<True>. Actual:<False>.
  Stack Trace:
     at TestProject.UnitTest2.TestMethod1(Context context, Boolean expected) in D:\Projects\ConsoleApp1\TestProject\UnitTest2.cs:line 19

  Standard Output Messages:
 Value1: 'False', Value2: 'False'; Expected: True;


  Failed {Value1: 'True', Value2: 'True'}; Expected: True; [< 1 ms]
  Error Message:
   Assert.AreEqual failed. Expected:<True>. Actual:<False>.
  Stack Trace:
     at TestProject.UnitTest2.TestMethod1(Context context, Boolean expected) in D:\Projects\ConsoleApp1\TestProject\UnitTest2.cs:line 19

  Standard Output Messages:
 Value1: 'False', Value2: 'False'; Expected: True;



Test Run Failed.
Total tests: 4
     Passed: 1
     Failed: 3
 Total time: 0.8083 Seconds
```

By the way: I opened also [an issue for VS](https://developercommunity.visualstudio.com/t/dynamicdata-not-all-tests-executed/1472637), because I first found am example where it worked with `vstest.console.exe` but failed with VS. But it looks like the bug is here.

**Comment by Haplois** [comment]
Thank you for reporting this issue. It's caused by the changes on how we handle tests with data sources after version 2.2.3. Please update to version 2.2.6 and opt-out out of this behavior as described [here][1].

[1]: https://github.com/microsoft/testfx/issues/905#issuecomment-907775327
