### ISSUE TITLE
Async Initialize methods swallow outer exception and stacktrace 

### ISSUE THREAD

**Issue by gao-artur** [microsoft/testfx#939]
Consider following code:
```
[TestInitialize]
public async Task InitAsync()
{
    await ThrowAsync();
}

private static Task ThrowAsync()
{
    return Task.FromException<Exception>(new Exception("Outer", new Exception("Inner")));
}
```

This code swallows outer exception with stacktrace and prints this message:
```
Initialization method UnitTests.InitTests.InitAsync threw exception. System.Exception: Inner.
Stacktrace is not available
```

The sync version:
```
[TestInitialize]
public void Init()
{
    Throw();
}

private static void Throw()
{
    throw new Exception("Outer", new Exception("Inner"));
}
```

Reports outer exception with stacktrace as expected:
```
Initialization method UnitTests.InitTests.Init threw exception. System.Exception: Outer ---> System.Exception: Inner.
    at UnitTests.InitTests.Throw() in C:\repo\UnitTests\InitTests.cs:line 43
   at UnitTests.InitTests.Init() in C:\repo\UnitTests\InitTests.cs:line 38
```

**Comment by Evangelink** [comment]
Hey @gao-artur,

We have found the issue and we will work on a fix. It seems not to be a regression as previous versions of MSTest have the same issue so we will postpone the fix for the version 3.1.0.

**Comment by Evangelink** [comment]
I have renamed the issue as the problem was more global and was impact the various init and cleanup.
